// Generates editable move-review tests from a CGR archive export.
// One generated file per game, named by the game's platform id. Usage:
//   bun scripts/gen-analysis-tests.ts [archive.json] [--outDir path] [--games 0,1]
//     [--types blunder,miss,mistake] [--limit 50] [--force]
//
// Every move is included unless --types narrows it. Files that already exist
// are skipped (pass --force to regenerate). Re-running with --force preserves
// any expectedMoveType / expectedComment you changed by hand (matched on id).

import { Chess } from "chess.js";

interface Args {
  archive: string;
  outDir: string;
  games: number[] | null;
  types: string[] | null;
  limit: number | null;
  force: boolean;
}

function parseArgs(argv: string[]): Args {
  const args: Args = {
    archive: "chess_archive.json",
    outDir: "tests/analysis",
    games: null,
    types: null,
    limit: null,
    force: false,
  };
  const rest: string[] = [];
  for (const a of argv) {
    if (a.startsWith("--outDir=")) args.outDir = a.slice(9);
    else if (a.startsWith("--games=")) args.games = a.slice(8).split(",").map(Number);
    else if (a.startsWith("--types=")) args.types = a.slice(8).split(",");
    else if (a.startsWith("--limit=")) args.limit = Number(a.slice(8));
    else if (a === "--force") args.force = true;
    else rest.push(a);
  }
  if (rest[0]) args.archive = rest[0];
  return args;
}

function idFromLink(pgn: string): string | undefined {
  const link = /\[Link "([^"]+)"\]/.exec(pgn)?.[1] ?? "";
  return link.match(/([A-Za-z0-9]+)\/?(?:\?.*)?$/)?.[1];
}

function safeId(raw: string): string {
  return raw.replace(/[^A-Za-z0-9-]+/g, "");
}

interface Preserved {
  expectedMoveType: string;
  expectedComment: string | null;
}

async function readPreserved(path: string): Promise<Map<number, Preserved>> {
  const found = new Map<number, Preserved>();
  const file = Bun.file(path);
  if (!(await file.exists())) return found;
  const src = await file.text();
  const blocks = src.split("const move_");
  for (const b of blocks.slice(1)) {
    const index = /moveIndex: (\d+)/.exec(b)?.[1];
    const type = /expectedMoveType: "([^"]+)"/.exec(b)?.[1];
    const commentRaw = /expectedComment: (null|"(?:[^"\\]|\\.)*")/.exec(b)?.[1];
    if (index !== undefined && type && commentRaw !== undefined) {
      found.set(Number(index), {
        expectedMoveType: type,
        expectedComment: commentRaw === "null" ? null : JSON.parse(commentRaw),
      });
    }
  }
  return found;
}

function emitString(v: unknown): string {
  return JSON.stringify(v, null, 2);
}

const IMPORTS = `import { test, describe } from "bun:test";
import { check } from "./helpers";
import type { GameMove } from "./helpers";
`;

function fileHeader(gameIndex: number, gameName: string, link: string, count: number): string {
  return `// Game ${gameIndex}: ${gameName}
// ${link}
// GENERATED by bun scripts/gen-analysis-tests.ts — do not hand-add moves here.
// Safe to edit: expectedMoveType / expectedComment per move (${count} moves).
// Re-running with --force preserves those two fields (matched on moveIndex).
`;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));

  const raw = await Bun.file(args.archive).text();
  const archive = JSON.parse(raw) as any[];
  const linkOf = (pgn: string): string => /\[Link "([^"]+)"\]/.exec(pgn)?.[1] ?? "";

  let totalKept = 0;

  for (const [gi, g] of archive.entries()) {
    if (args.games && !args.games.includes(gi)) continue;
    const fileId = safeId(g.id ?? idFromLink(g.pgn) ?? `game${gi}`);
    const outPath = `${args.outDir}/game.${fileId}.test.ts`;

    if (!args.force) {
      if (await Bun.file(outPath).exists()) {
        console.log(`skip ${outPath} (exists, use --force to regenerate)`);
        continue;
      }
    }
    const preserved = await readPreserved(outPath);

    const game = new Chess();
    game.loadPgn(g.pgn);
    const history = game.history({ verbose: true });
    const analysis = g.analysis as any[];
    const link = linkOf(g.pgn);

    const moves: string[] = [];
    const tests: string[] = [];
    let kept = 0;

    for (let j = 1; j < analysis.length; j++) {
      if (args.limit !== null && kept >= args.limit) break;
      const a = analysis[j];
      if (args.types && !args.types.includes(a.moveType)) continue;
      const mv = history[j - 1];
      if (!mv) continue;
      const p = analysis[j - 1];

      const probe = new Chess(mv.before);
      const made = probe.move({ from: mv.from, to: mv.to, promotion: mv.promotion });

      const ply = j;
      const moveNo = Math.ceil(ply / 2);
      const label = `${moveNo}${mv.color === "w" ? ". " : "... "}${mv.san}`;
      const constName = `move_${moveNo}_${mv.color}`;

      const prev = {
        eval: p.eval,
        bestMove: p.bestMove,
        ...(p.secondBest ? { secondBest: p.secondBest } : {}),
        hangingPieces: p.hangingPieces ?? { w: [], b: [] },
      };
      const stockfish: Record<string, unknown> = {
        bestMove: a.bestMove,
        lines: a.lines,
        eval: a.eval,
      };
      if (a.secondBest) stockfish.secondBest = a.secondBest;

      const keep = preserved.get(j - 1);
      const expectedMoveType = keep?.expectedMoveType ?? a.moveType;
      const expectedComment = keep ? keep.expectedComment : (a.moveComment ?? null);

      const position = {
        color: mv.color,
        san: mv.san,
        before: mv.before,
        after: mv.after,
        from: mv.from,
        to: mv.to,
        piece: mv.piece,
        flags: mv.flags,
        lan: mv.lan,
        isBigPawn: made.isBigPawn(),
        isCapture: made.isCapture(),
        isEnPassant: made.isEnPassant(),
        isKingsideCastle: made.isKingsideCastle(),
        isPromotion: made.isPromotion(),
        isQueensideCastle: made.isQueensideCastle(),
      };

      moves.push(
        [
          `const ${constName}: GameMove = {`,
                    `  analyzerMoveType: ${JSON.stringify(a.moveType)},`,
          `  expectedMoveType: ${JSON.stringify(expectedMoveType)},`,
          `  expectedComment: ${expectedComment === null ? "null" : JSON.stringify(expectedComment)},`,
          `  moveIndex: ${j - 1},`,
          `  position: ${emitString(position)},`,
          `  stockfish: ${emitString(stockfish)},`,
          `  prev: ${emitString(prev)},`,
          `};`,
        ].join("\n")
      );
      tests.push(`  test(${JSON.stringify(label)}, async () => {\n    await check(${constName});\n  });`);
      kept++;
    }

    if (kept === 0) continue;
    const out =
      `${IMPORTS}\n${fileHeader(gi, g.name, link, kept)}${moves.join("\n\n")}\n\ndescribe(${JSON.stringify(`Game ${gi}`)}, () => {\n${tests.join("\n\n")}\n});\n`;
    await Bun.write(outPath, out);
    console.log(`${outPath}: ${kept} moves`);
    totalKept += kept;
  }

  console.log(`total: ${totalKept} moves`);
}

main();
