import { test, describe } from "bun:test";
import { check } from "./helpers";
import type { GameMove } from "./helpers";

// Game 2: bibekbhusal (1560) VS mem1003 (1589)
// https://www.chess.com/game/live/169989950570
// GENERATED by bun scripts/gen-analysis-tests.ts — do not hand-add moves here.
// Safe to edit: expectedMoveType / expectedComment per move (64 moves).
// Re-running with --force preserves those two fields (matched on moveIndex).
const move_1_w: GameMove = {
  analyzerMoveType: "best",
  expectedMoveType: "best",
  expectedComment: null,
  moveIndex: 0,
  position: {
  "color": "w",
  "san": "e4",
  "before": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
  "after": "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1",
  "from": "e2",
  "to": "e4",
  "piece": "p",
  "flags": "b",
  "lan": "e2e4",
  "isBigPawn": true,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "c5",
  "lines": [
    "c5",
    "Nf3",
    "d6",
    "Nc3",
    "Nc6",
    "d4",
    "cxd4",
    "Nxd4",
    "g6",
    "Be3",
    "Nf6",
    "Qd2"
  ],
  "eval": {
    "type": "cp",
    "value": 28
  },
  "secondBest": {
    "lines": [
      "e7e5",
      "g1f3",
      "b8c6",
      "b1c3",
      "g8f6",
      "f1b5",
      "f8b4",
      "c3d5",
      "f6d5",
      "e4d5",
      "c6e7",
      "c2c3"
    ],
    "eval": {
      "type": "cp",
      "value": 37
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 34
  },
  "bestMove": "e4",
  "secondBest": {
    "lines": [
      "d2d4",
      "d7d5",
      "c2c4",
      "e7e6",
      "g1f3",
      "g8f6",
      "g2g3",
      "c7c5",
      "c4d5",
      "f6d5",
      "f1g2",
      "f8e7",
      "b1c3",
      "e8g8",
      "e1g1"
    ],
    "eval": {
      "type": "cp",
      "value": 34
    }
  },
  "hangingPieces": {
    "b": [],
    "w": []
  }
},
};

const move_1_b: GameMove = {
  analyzerMoveType: "book",
  expectedMoveType: "book",
  expectedComment: null,
  moveIndex: 1,
  position: {
  "color": "b",
  "san": "e5",
  "before": "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1",
  "after": "rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2",
  "from": "e7",
  "to": "e5",
  "piece": "p",
  "flags": "b",
  "lan": "e7e5",
  "isBigPawn": true,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Nf3",
  "lines": [
    "Nf3",
    "Nc6",
    "d4",
    "exd4",
    "Nxd4",
    "Nf6",
    "Nxc6",
    "dxc6",
    "Qxd8+",
    "Kxd8",
    "f3",
    "Be6",
    "h4",
    "a5",
    "Be3",
    "Nd7",
    "Kf2",
    "b6"
  ],
  "eval": {
    "type": "cp",
    "value": 35
  },
  "secondBest": {
    "lines": [
      "b1c3",
      "g8f6",
      "g1f3",
      "b8c6",
      "f1b5",
      "f8c5",
      "d2d3",
      "e8g8",
      "b5c6",
      "d7c6",
      "a2a4",
      "f8e8",
      "h2h3",
      "a7a5",
      "e1g1"
    ],
    "eval": {
      "type": "cp",
      "value": 19
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 28
  },
  "bestMove": "c5",
  "secondBest": {
    "lines": [
      "e7e5",
      "g1f3",
      "b8c6",
      "b1c3",
      "g8f6",
      "f1b5",
      "f8b4",
      "c3d5",
      "f6d5",
      "e4d5",
      "c6e7",
      "c2c3"
    ],
    "eval": {
      "type": "cp",
      "value": 37
    }
  },
  "hangingPieces": {
    "b": [],
    "w": []
  }
},
};

const move_2_w: GameMove = {
  analyzerMoveType: "book",
  expectedMoveType: "book",
  expectedComment: null,
  moveIndex: 2,
  position: {
  "color": "w",
  "san": "Nc3",
  "before": "rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2",
  "after": "rnbqkbnr/pppp1ppp/8/4p3/4P3/2N5/PPPP1PPP/R1BQKBNR b KQkq - 1 2",
  "from": "b1",
  "to": "c3",
  "piece": "n",
  "flags": "n",
  "lan": "b1c3",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Nc6",
  "lines": [
    "Nc6",
    "Bc4",
    "Nf6",
    "a3",
    "d6",
    "d3"
  ],
  "eval": {
    "type": "cp",
    "value": 19
  },
  "secondBest": {
    "lines": [
      "f8c5",
      "g1f3",
      "d7d6",
      "d2d4",
      "e5d4",
      "f3d4",
      "g8f6",
      "c1g5",
      "e8g8",
      "d1d2",
      "h7h6"
    ],
    "eval": {
      "type": "cp",
      "value": 22
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 35
  },
  "bestMove": "Nf3",
  "secondBest": {
    "lines": [
      "b1c3",
      "g8f6",
      "g1f3",
      "b8c6",
      "f1b5",
      "f8c5",
      "d2d3",
      "e8g8",
      "b5c6",
      "d7c6",
      "a2a4",
      "f8e8",
      "h2h3",
      "a7a5",
      "e1g1"
    ],
    "eval": {
      "type": "cp",
      "value": 19
    }
  },
  "hangingPieces": {
    "w": [],
    "b": []
  }
},
};

const move_2_b: GameMove = {
  analyzerMoveType: "book",
  expectedMoveType: "book",
  expectedComment: null,
  moveIndex: 3,
  position: {
  "color": "b",
  "san": "Bc5",
  "before": "rnbqkbnr/pppp1ppp/8/4p3/4P3/2N5/PPPP1PPP/R1BQKBNR b KQkq - 1 2",
  "after": "rnbqk1nr/pppp1ppp/8/2b1p3/4P3/2N5/PPPP1PPP/R1BQKBNR w KQkq - 2 3",
  "from": "f8",
  "to": "c5",
  "piece": "b",
  "flags": "n",
  "lan": "f8c5",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Nf3",
  "lines": [
    "Nf3",
    "d6",
    "Na4",
    "Bb6",
    "Nxb6",
    "axb6",
    "d4",
    "exd4",
    "Bb5+",
    "Bd7",
    "Nxd4",
    "Nc6",
    "Nf5",
    "Qf6"
  ],
  "eval": {
    "type": "cp",
    "value": 28
  },
  "secondBest": {
    "lines": [
      "f1c4",
      "g8f6",
      "g1f3",
      "d7d6",
      "d2d4",
      "e5d4",
      "f3d4",
      "e8g8",
      "e1g1",
      "b8c6",
      "d4b3",
      "c5b6",
      "a2a4",
      "c8g4",
      "c4e2",
      "g4e2",
      "d1e2"
    ],
    "eval": {
      "type": "cp",
      "value": 14
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 19
  },
  "bestMove": "Nc6",
  "secondBest": {
    "lines": [
      "f8c5",
      "g1f3",
      "d7d6",
      "d2d4",
      "e5d4",
      "f3d4",
      "g8f6",
      "c1g5",
      "e8g8",
      "d1d2",
      "h7h6"
    ],
    "eval": {
      "type": "cp",
      "value": 22
    }
  },
  "hangingPieces": {
    "b": [],
    "w": []
  }
},
};

const move_3_w: GameMove = {
  analyzerMoveType: "good",
  expectedMoveType: "good",
  expectedComment: null,
  moveIndex: 4,
  position: {
  "color": "w",
  "san": "Bc4",
  "before": "rnbqk1nr/pppp1ppp/8/2b1p3/4P3/2N5/PPPP1PPP/R1BQKBNR w KQkq - 2 3",
  "after": "rnbqk1nr/pppp1ppp/8/2b1p3/2B1P3/2N5/PPPP1PPP/R1BQK1NR b KQkq - 3 3",
  "from": "f1",
  "to": "c4",
  "piece": "b",
  "flags": "n",
  "lan": "f1c4",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Nf6",
  "lines": [
    "Nf6",
    "Nf3",
    "d6",
    "O-O",
    "O-O",
    "d4",
    "exd4",
    "Nxd4",
    "h6",
    "Re1"
  ],
  "eval": {
    "type": "cp",
    "value": 5
  },
  "secondBest": {
    "lines": [
      "b8c6",
      "d1h5",
      "g7g6",
      "h5f3",
      "g8f6",
      "g1e2",
      "c6b4"
    ],
    "eval": {
      "type": "cp",
      "value": 15
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 28
  },
  "bestMove": "Nf3",
  "secondBest": {
    "lines": [
      "f1c4",
      "g8f6",
      "g1f3",
      "d7d6",
      "d2d4",
      "e5d4",
      "f3d4",
      "e8g8",
      "e1g1",
      "b8c6",
      "d4b3",
      "c5b6",
      "a2a4",
      "c8g4",
      "c4e2",
      "g4e2",
      "d1e2"
    ],
    "eval": {
      "type": "cp",
      "value": 14
    }
  },
  "hangingPieces": {
    "w": [],
    "b": []
  }
},
};

const move_3_b: GameMove = {
  analyzerMoveType: "good",
  expectedMoveType: "good",
  expectedComment: null,
  moveIndex: 5,
  position: {
  "color": "b",
  "san": "d6",
  "before": "rnbqk1nr/pppp1ppp/8/2b1p3/2B1P3/2N5/PPPP1PPP/R1BQK1NR b KQkq - 3 3",
  "after": "rnbqk1nr/ppp2ppp/3p4/2b1p3/2B1P3/2N5/PPPP1PPP/R1BQK1NR w KQkq - 0 4",
  "from": "d7",
  "to": "d6",
  "piece": "p",
  "flags": "n",
  "lan": "d7d6",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Qh5",
  "lines": [
    "Qh5",
    "Qf6",
    "f4",
    "Be6",
    "Bxe6",
    "Qxe6",
    "Qg5",
    "Qh6",
    "Qxh6",
    "Nxh6",
    "Nf3"
  ],
  "eval": {
    "type": "cp",
    "value": 27
  },
  "secondBest": {
    "lines": [
      "c3a4",
      "c5b6",
      "a4b6",
      "a7b6",
      "g1e2",
      "b8c6",
      "d2d4",
      "e5d4",
      "e2d4",
      "g8f6",
      "e1g1",
      "e8g8",
      "c1g5"
    ],
    "eval": {
      "type": "cp",
      "value": 23
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 5
  },
  "bestMove": "Nf6",
  "secondBest": {
    "lines": [
      "b8c6",
      "d1h5",
      "g7g6",
      "h5f3",
      "g8f6",
      "g1e2",
      "c6b4"
    ],
    "eval": {
      "type": "cp",
      "value": 15
    }
  },
  "hangingPieces": {
    "b": [],
    "w": []
  }
},
};

const move_4_w: GameMove = {
  analyzerMoveType: "inaccuracy",
  expectedMoveType: "inaccuracy",
  expectedComment: null,
  moveIndex: 6,
  position: {
  "color": "w",
  "san": "f4",
  "before": "rnbqk1nr/ppp2ppp/3p4/2b1p3/2B1P3/2N5/PPPP1PPP/R1BQK1NR w KQkq - 0 4",
  "after": "rnbqk1nr/ppp2ppp/3p4/2b1p3/2B1PP2/2N5/PPPP2PP/R1BQK1NR b KQkq - 0 4",
  "from": "f2",
  "to": "f4",
  "piece": "p",
  "flags": "b",
  "lan": "f2f4",
  "isBigPawn": true,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Bxg1",
  "lines": [
    "Bxg1",
    "Rxg1",
    "Qh4+",
    "Kf1",
    "Nf6",
    "d4",
    "Ng4"
  ],
  "eval": {
    "type": "cp",
    "value": -141
  },
  "secondBest": {
    "lines": [
      "b8c6",
      "g1f3",
      "g8f6",
      "f4e5",
      "d6e5",
      "h1f1",
      "e8g8",
      "d2d3",
      "c6d4",
      "c1g5",
      "c8e6",
      "g5f6",
      "d8f6",
      "f3d4",
      "e6c4",
      "f1f6"
    ],
    "eval": {
      "type": "cp",
      "value": -44
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 27
  },
  "bestMove": "Qh5",
  "secondBest": {
    "lines": [
      "c3a4",
      "c5b6",
      "a4b6",
      "a7b6",
      "g1e2",
      "b8c6",
      "d2d4",
      "e5d4",
      "e2d4",
      "g8f6",
      "e1g1",
      "e8g8",
      "c1g5"
    ],
    "eval": {
      "type": "cp",
      "value": 23
    }
  },
  "hangingPieces": {
    "w": [],
    "b": []
  }
},
};

const move_4_b: GameMove = {
  analyzerMoveType: "mistake",
  expectedMoveType: "mistake",
  expectedComment: null,
  moveIndex: 7,
  position: {
  "color": "b",
  "san": "exf4",
  "before": "rnbqk1nr/ppp2ppp/3p4/2b1p3/2B1PP2/2N5/PPPP2PP/R1BQK1NR b KQkq - 0 4",
  "after": "rnbqk1nr/ppp2ppp/3p4/2b5/2B1Pp2/2N5/PPPP2PP/R1BQK1NR w KQkq - 0 5",
  "from": "e5",
  "to": "f4",
  "piece": "p",
  "flags": "c",
  "lan": "e5f4",
  "isBigPawn": false,
  "isCapture": true,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "d4",
  "lines": [
    "d4",
    "Qh4+",
    "Kf1",
    "Bb6",
    "Nf3",
    "Qh5",
    "Nd5",
    "Be6",
    "Bxf4",
    "Nf6",
    "Qe1",
    "Nc6"
  ],
  "eval": {
    "type": "cp",
    "value": 60
  },
  "secondBest": {
    "lines": [
      "g1f3",
      "c8g4",
      "d2d4",
      "g4f3",
      "d1f3",
      "c5d4",
      "c1f4",
      "b8c6",
      "e1c1",
      "g8f6",
      "c3d5",
      "f6d5",
      "e4d5",
      "c6e5",
      "f3b3",
      "e5c4",
      "d1d4"
    ],
    "eval": {
      "type": "cp",
      "value": 50
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": -141
  },
  "bestMove": "Bxg1",
  "secondBest": {
    "lines": [
      "b8c6",
      "g1f3",
      "g8f6",
      "f4e5",
      "d6e5",
      "h1f1",
      "e8g8",
      "d2d3",
      "c6d4",
      "c1g5",
      "c8e6",
      "g5f6",
      "d8f6",
      "f3d4",
      "e6c4",
      "f1f6"
    ],
    "eval": {
      "type": "cp",
      "value": -44
    }
  },
  "hangingPieces": {
    "b": [],
    "w": [
      "f4"
    ]
  }
},
};

const move_5_w: GameMove = {
  analyzerMoveType: "inaccuracy",
  expectedMoveType: "inaccuracy",
  expectedComment: null,
  moveIndex: 8,
  position: {
  "color": "w",
  "san": "Nf3",
  "before": "rnbqk1nr/ppp2ppp/3p4/2b5/2B1Pp2/2N5/PPPP2PP/R1BQK1NR w KQkq - 0 5",
  "after": "rnbqk1nr/ppp2ppp/3p4/2b5/2B1Pp2/2N2N2/PPPP2PP/R1BQK2R b KQkq - 1 5",
  "from": "g1",
  "to": "f3",
  "piece": "n",
  "flags": "n",
  "lan": "g1f3",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Nc6",
  "lines": [
    "Nc6",
    "d4",
    "Nxd4",
    "Nxd4",
    "Qh4+",
    "Kf1",
    "Nf6",
    "Qd2",
    "Bg4",
    "Nf3",
    "Bxf3",
    "gxf3"
  ],
  "eval": {
    "type": "cp",
    "value": 5
  },
  "secondBest": {
    "lines": [
      "c8g4",
      "d2d4",
      "g4f3",
      "d1f3",
      "c5d4",
      "c1f4",
      "b8c6",
      "e1c1",
      "g8f6",
      "c3d5",
      "f6d5",
      "e4d5",
      "c6e5",
      "f3e4"
    ],
    "eval": {
      "type": "cp",
      "value": 42
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 60
  },
  "bestMove": "d4",
  "secondBest": {
    "lines": [
      "g1f3",
      "c8g4",
      "d2d4",
      "g4f3",
      "d1f3",
      "c5d4",
      "c1f4",
      "b8c6",
      "e1c1",
      "g8f6",
      "c3d5",
      "f6d5",
      "e4d5",
      "c6e5",
      "f3b3",
      "e5c4",
      "d1d4"
    ],
    "eval": {
      "type": "cp",
      "value": 50
    }
  },
  "hangingPieces": {
    "w": [],
    "b": []
  }
},
};

const move_5_b: GameMove = {
  analyzerMoveType: "inaccuracy",
  expectedMoveType: "inaccuracy",
  expectedComment: null,
  moveIndex: 9,
  position: {
  "color": "b",
  "san": "Nf6",
  "before": "rnbqk1nr/ppp2ppp/3p4/2b5/2B1Pp2/2N2N2/PPPP2PP/R1BQK2R b KQkq - 1 5",
  "after": "rnbqk2r/ppp2ppp/3p1n2/2b5/2B1Pp2/2N2N2/PPPP2PP/R1BQK2R w KQkq - 2 6",
  "from": "g8",
  "to": "f6",
  "piece": "n",
  "flags": "n",
  "lan": "g8f6",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "d4",
  "lines": [
    "d4",
    "Bb4",
    "Bd3",
    "Bxc3+",
    "bxc3",
    "O-O",
    "O-O",
    "Nh5",
    "Nd2",
    "Qg5"
  ],
  "eval": {
    "type": "cp",
    "value": 72
  },
  "secondBest": {
    "lines": [
      "a2a3",
      "e8g8",
      "d2d4",
      "c5b6",
      "c1f4",
      "f6e4",
      "c3e4",
      "d6d5",
      "f4g5",
      "f7f6"
    ],
    "eval": {
      "type": "cp",
      "value": 44
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 5
  },
  "bestMove": "Nc6",
  "secondBest": {
    "lines": [
      "c8g4",
      "d2d4",
      "g4f3",
      "d1f3",
      "c5d4",
      "c1f4",
      "b8c6",
      "e1c1",
      "g8f6",
      "c3d5",
      "f6d5",
      "e4d5",
      "c6e5",
      "f3e4"
    ],
    "eval": {
      "type": "cp",
      "value": 42
    }
  },
  "hangingPieces": {
    "b": [],
    "w": []
  }
},
};

const move_6_w: GameMove = {
  analyzerMoveType: "best",
  expectedMoveType: "best",
  expectedComment: null,
  moveIndex: 10,
  position: {
  "color": "w",
  "san": "d4",
  "before": "rnbqk2r/ppp2ppp/3p1n2/2b5/2B1Pp2/2N2N2/PPPP2PP/R1BQK2R w KQkq - 2 6",
  "after": "rnbqk2r/ppp2ppp/3p1n2/2b5/2BPPp2/2N2N2/PPP3PP/R1BQK2R b KQkq - 0 6",
  "from": "d2",
  "to": "d4",
  "piece": "p",
  "flags": "b",
  "lan": "d2d4",
  "isBigPawn": true,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Bb4",
  "lines": [
    "Bb4",
    "Bd3",
    "Bxc3+",
    "bxc3",
    "Nh5",
    "O-O",
    "Bg4",
    "Qe1",
    "O-O",
    "Rb1",
    "Nd7",
    "Rxb7"
  ],
  "eval": {
    "type": "cp",
    "value": 69
  },
  "secondBest": {
    "lines": [
      "c5b6",
      "c1f4",
      "c8e6",
      "d1d3",
      "e6c4",
      "d3c4",
      "e8g8",
      "f4g5",
      "h7h6",
      "g5h4",
      "b8d7",
      "e1c1",
      "d8e8",
      "h1e1",
      "b6a5",
      "e4e5"
    ],
    "eval": {
      "type": "cp",
      "value": 110
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 72
  },
  "bestMove": "d4",
  "secondBest": {
    "lines": [
      "a2a3",
      "e8g8",
      "d2d4",
      "c5b6",
      "c1f4",
      "f6e4",
      "c3e4",
      "d6d5",
      "f4g5",
      "f7f6"
    ],
    "eval": {
      "type": "cp",
      "value": 44
    }
  },
  "hangingPieces": {
    "w": [],
    "b": []
  }
},
};

const move_6_b: GameMove = {
  analyzerMoveType: "good",
  expectedMoveType: "good",
  expectedComment: null,
  moveIndex: 11,
  position: {
  "color": "b",
  "san": "Bb6",
  "before": "rnbqk2r/ppp2ppp/3p1n2/2b5/2BPPp2/2N2N2/PPP3PP/R1BQK2R b KQkq - 0 6",
  "after": "rnbqk2r/ppp2ppp/1b1p1n2/8/2BPPp2/2N2N2/PPP3PP/R1BQK2R w KQkq - 1 7",
  "from": "c5",
  "to": "b6",
  "piece": "b",
  "flags": "n",
  "lan": "c5b6",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Bxf4",
  "lines": [
    "Bxf4",
    "Be6",
    "Qd3",
    "Bxc4",
    "Qxc4",
    "O-O",
    "O-O-O",
    "Nxe4",
    "Nxe4",
    "d5",
    "Qd3",
    "dxe4",
    "Qxe4",
    "Nc6",
    "Ng5"
  ],
  "eval": {
    "type": "cp",
    "value": 112
  },
  "secondBest": {
    "lines": [
      "d1d3",
      "f6h5",
      "c3d5",
      "e8g8",
      "d5f4",
      "c8g4",
      "c2c3",
      "c7c6",
      "e1g1",
      "b8d7",
      "f4h5",
      "g4h5",
      "c1g5"
    ],
    "eval": {
      "type": "cp",
      "value": 72
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 69
  },
  "bestMove": "Bb4",
  "secondBest": {
    "lines": [
      "c5b6",
      "c1f4",
      "c8e6",
      "d1d3",
      "e6c4",
      "d3c4",
      "e8g8",
      "f4g5",
      "h7h6",
      "g5h4",
      "b8d7",
      "e1c1",
      "d8e8",
      "h1e1",
      "b6a5",
      "e4e5"
    ],
    "eval": {
      "type": "cp",
      "value": 110
    }
  },
  "hangingPieces": {
    "b": [
      "f4"
    ],
    "w": []
  }
},
};

const move_7_w: GameMove = {
  analyzerMoveType: "inaccuracy",
  expectedMoveType: "inaccuracy",
  expectedComment: null,
  moveIndex: 12,
  position: {
  "color": "w",
  "san": "O-O",
  "before": "rnbqk2r/ppp2ppp/1b1p1n2/8/2BPPp2/2N2N2/PPP3PP/R1BQK2R w KQkq - 1 7",
  "after": "rnbqk2r/ppp2ppp/1b1p1n2/8/2BPPp2/2N2N2/PPP3PP/R1BQ1RK1 b kq - 2 7",
  "from": "e1",
  "to": "g1",
  "piece": "k",
  "flags": "k",
  "lan": "e1g1",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": true,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Bg4",
  "lines": [
    "Bg4",
    "Bxf4",
    "Nc6",
    "Be3",
    "Ne5",
    "Be2",
    "Nxf3+",
    "Bxf3",
    "Bxf3",
    "Qxf3",
    "O-O"
  ],
  "eval": {
    "type": "cp",
    "value": 59
  },
  "secondBest": {
    "lines": [
      "b8c6",
      "c1f4",
      "c8g4",
      "f4e3",
      "e8g8",
      "h2h3",
      "g4e6",
      "c4b3",
      "e6b3",
      "a2b3",
      "d8e8",
      "f3g5",
      "h7h6",
      "f1f6",
      "h6g5",
      "f6f3",
      "f7f6"
    ],
    "eval": {
      "type": "cp",
      "value": 64
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 112
  },
  "bestMove": "Bxf4",
  "secondBest": {
    "lines": [
      "d1d3",
      "f6h5",
      "c3d5",
      "e8g8",
      "d5f4",
      "c8g4",
      "c2c3",
      "c7c6",
      "e1g1",
      "b8d7",
      "f4h5",
      "g4h5",
      "c1g5"
    ],
    "eval": {
      "type": "cp",
      "value": 72
    }
  },
  "hangingPieces": {
    "w": [],
    "b": [
      "f4"
    ]
  }
},
};

const move_7_b: GameMove = {
  analyzerMoveType: "good",
  expectedMoveType: "good",
  expectedComment: null,
  moveIndex: 13,
  position: {
  "color": "b",
  "san": "O-O",
  "before": "rnbqk2r/ppp2ppp/1b1p1n2/8/2BPPp2/2N2N2/PPP3PP/R1BQ1RK1 b kq - 2 7",
  "after": "rnbq1rk1/ppp2ppp/1b1p1n2/8/2BPPp2/2N2N2/PPP3PP/R1BQ1RK1 w - - 3 8",
  "from": "e8",
  "to": "g8",
  "piece": "k",
  "flags": "k",
  "lan": "e8g8",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": true,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Bxf4",
  "lines": [
    "Bxf4",
    "Be6",
    "Be2",
    "Nbd7",
    "Kh1",
    "Ba5",
    "Bd3",
    "Bg4",
    "h3",
    "Bh5"
  ],
  "eval": {
    "type": "cp",
    "value": 99
  },
  "secondBest": {
    "lines": [
      "g1h1",
      "c8e6",
      "c4e2",
      "b6a5",
      "f3g5",
      "h7h6",
      "g5e6",
      "f7e6",
      "c1f4",
      "a5c3"
    ],
    "eval": {
      "type": "cp",
      "value": 47
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 59
  },
  "bestMove": "Bg4",
  "secondBest": {
    "lines": [
      "b8c6",
      "c1f4",
      "c8g4",
      "f4e3",
      "e8g8",
      "h2h3",
      "g4e6",
      "c4b3",
      "e6b3",
      "a2b3",
      "d8e8",
      "f3g5",
      "h7h6",
      "f1f6",
      "h6g5",
      "f6f3",
      "f7f6"
    ],
    "eval": {
      "type": "cp",
      "value": 64
    }
  },
  "hangingPieces": {
    "b": [
      "f4"
    ],
    "w": []
  }
},
};

const move_8_w: GameMove = {
  analyzerMoveType: "best",
  expectedMoveType: "best",
  expectedComment: null,
  moveIndex: 14,
  position: {
  "color": "w",
  "san": "Bxf4",
  "before": "rnbq1rk1/ppp2ppp/1b1p1n2/8/2BPPp2/2N2N2/PPP3PP/R1BQ1RK1 w - - 3 8",
  "after": "rnbq1rk1/ppp2ppp/1b1p1n2/8/2BPPB2/2N2N2/PPP3PP/R2Q1RK1 b - - 0 8",
  "from": "c1",
  "to": "f4",
  "piece": "b",
  "flags": "c",
  "lan": "c1f4",
  "isBigPawn": false,
  "isCapture": true,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Nc6",
  "lines": [
    "Nc6",
    "Kh1",
    "Bg4",
    "Be3",
    "Nxe4",
    "Nxe4",
    "d5",
    "Nf6+",
    "Qxf6",
    "Bxd5",
    "Rae8",
    "Qd2",
    "Be6",
    "Bxc6",
    "bxc6",
    "Ne5",
    "Qh4"
  ],
  "eval": {
    "type": "cp",
    "value": 64
  },
  "secondBest": {
    "lines": [
      "c8e6",
      "c4e2",
      "b8c6",
      "g1h1",
      "e6g4",
      "f4g5",
      "h7h6",
      "g5f6",
      "d8f6",
      "c3d5",
      "f6d8",
      "c2c3",
      "c6e7"
    ],
    "eval": {
      "type": "cp",
      "value": 84
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 99
  },
  "bestMove": "Bxf4",
  "secondBest": {
    "lines": [
      "g1h1",
      "c8e6",
      "c4e2",
      "b6a5",
      "f3g5",
      "h7h6",
      "g5e6",
      "f7e6",
      "c1f4",
      "a5c3"
    ],
    "eval": {
      "type": "cp",
      "value": 47
    }
  },
  "hangingPieces": {
    "w": [],
    "b": [
      "f4"
    ]
  }
},
};

const move_8_b: GameMove = {
  analyzerMoveType: "good",
  expectedMoveType: "good",
  expectedComment: null,
  moveIndex: 15,
  position: {
  "color": "b",
  "san": "Bg4",
  "before": "rnbq1rk1/ppp2ppp/1b1p1n2/8/2BPPB2/2N2N2/PPP3PP/R2Q1RK1 b - - 0 8",
  "after": "rn1q1rk1/ppp2ppp/1b1p1n2/8/2BPPBb1/2N2N2/PPP3PP/R2Q1RK1 w - - 1 9",
  "from": "c8",
  "to": "g4",
  "piece": "b",
  "flags": "n",
  "lan": "c8g4",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "h3",
  "lines": [
    "h3",
    "Be6",
    "Be2",
    "Nc6",
    "Bg5",
    "h6",
    "Bh4",
    "Ne5",
    "a4",
    "Ng6",
    "Bxf6",
    "Qxf6",
    "a5"
  ],
  "eval": {
    "type": "cp",
    "value": 99
  },
  "secondBest": {
    "lines": [
      "g1h1",
      "b8c6",
      "f4g5",
      "b6d4",
      "c3d5",
      "d4b2",
      "a1b1",
      "h7h6",
      "g5h4",
      "b2e5",
      "d1d3",
      "g4f3",
      "f1f3",
      "g7g5",
      "d5f6",
      "e5f6"
    ],
    "eval": {
      "type": "cp",
      "value": 91
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 64
  },
  "bestMove": "Nc6",
  "secondBest": {
    "lines": [
      "c8e6",
      "c4e2",
      "b8c6",
      "g1h1",
      "e6g4",
      "f4g5",
      "h7h6",
      "g5f6",
      "d8f6",
      "c3d5",
      "f6d8",
      "c2c3",
      "c6e7"
    ],
    "eval": {
      "type": "cp",
      "value": 84
    }
  },
  "hangingPieces": {
    "b": [],
    "w": []
  }
},
};

const move_9_w: GameMove = {
  analyzerMoveType: "good",
  expectedMoveType: "good",
  expectedComment: null,
  moveIndex: 16,
  position: {
  "color": "w",
  "san": "Qd3",
  "before": "rn1q1rk1/ppp2ppp/1b1p1n2/8/2BPPBb1/2N2N2/PPP3PP/R2Q1RK1 w - - 1 9",
  "after": "rn1q1rk1/ppp2ppp/1b1p1n2/8/2BPPBb1/2NQ1N2/PPP3PP/R4RK1 b - - 2 9",
  "from": "d1",
  "to": "d3",
  "piece": "q",
  "flags": "n",
  "lan": "d1d3",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Nc6",
  "lines": [
    "Nc6",
    "Be3",
    "Nb4",
    "Qd2",
    "d5",
    "Bb3",
    "dxe4",
    "Ne5",
    "Be6",
    "Rxf6"
  ],
  "eval": {
    "type": "cp",
    "value": 55
  },
  "secondBest": {
    "lines": [
      "g4f3",
      "g2f3",
      "b8c6",
      "f4e3",
      "c6a5",
      "b2b3",
      "a5c4",
      "b3c4"
    ],
    "eval": {
      "type": "cp",
      "value": 58
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 99
  },
  "bestMove": "h3",
  "secondBest": {
    "lines": [
      "g1h1",
      "b8c6",
      "f4g5",
      "b6d4",
      "c3d5",
      "d4b2",
      "a1b1",
      "h7h6",
      "g5h4",
      "b2e5",
      "d1d3",
      "g4f3",
      "f1f3",
      "g7g5",
      "d5f6",
      "e5f6"
    ],
    "eval": {
      "type": "cp",
      "value": 91
    }
  },
  "hangingPieces": {
    "w": [],
    "b": []
  }
},
};

const move_9_b: GameMove = {
  analyzerMoveType: "best",
  expectedMoveType: "best",
  expectedComment: null,
  moveIndex: 17,
  position: {
  "color": "b",
  "san": "Nc6",
  "before": "rn1q1rk1/ppp2ppp/1b1p1n2/8/2BPPBb1/2NQ1N2/PPP3PP/R4RK1 b - - 2 9",
  "after": "r2q1rk1/ppp2ppp/1bnp1n2/8/2BPPBb1/2NQ1N2/PPP3PP/R4RK1 w - - 3 10",
  "from": "b8",
  "to": "c6",
  "piece": "n",
  "flags": "n",
  "lan": "b8c6",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Be3",
  "lines": [
    "Be3",
    "Nb4",
    "Qd2",
    "d5",
    "exd5",
    "Nbxd5",
    "Bg5",
    "Nxc3",
    "bxc3",
    "Be6",
    "Bxf6",
    "Qxf6",
    "Ng5",
    "Qh6",
    "Bxe6",
    "fxe6"
  ],
  "eval": {
    "type": "cp",
    "value": 48
  },
  "secondBest": {
    "lines": [
      "c4b5",
      "c6b4",
      "d3d1",
      "d6d5",
      "e4e5",
      "f6e4",
      "h2h3"
    ],
    "eval": {
      "type": "cp",
      "value": -5
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 55
  },
  "bestMove": "Nc6",
  "secondBest": {
    "lines": [
      "g4f3",
      "g2f3",
      "b8c6",
      "f4e3",
      "c6a5",
      "b2b3",
      "a5c4",
      "b3c4"
    ],
    "eval": {
      "type": "cp",
      "value": 58
    }
  },
  "hangingPieces": {
    "b": [],
    "w": []
  }
},
};

const move_10_w: GameMove = {
  analyzerMoveType: "inaccuracy",
  expectedMoveType: "inaccuracy",
  expectedComment: null,
  moveIndex: 18,
  position: {
  "color": "w",
  "san": "Ne2",
  "before": "r2q1rk1/ppp2ppp/1bnp1n2/8/2BPPBb1/2NQ1N2/PPP3PP/R4RK1 w - - 3 10",
  "after": "r2q1rk1/ppp2ppp/1bnp1n2/8/2BPPBb1/3Q1N2/PPP1N1PP/R4RK1 b - - 4 10",
  "from": "c3",
  "to": "e2",
  "piece": "n",
  "flags": "n",
  "lan": "c3e2",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Qe8",
  "lines": [
    "Qe8",
    "c3",
    "Qxe4",
    "Qd2",
    "Ne5",
    "Ng3",
    "Nxc4",
    "Nxe4",
    "Nxd2",
    "Nxf6+",
    "gxf6",
    "Nxd2",
    "Rfe8"
  ],
  "eval": {
    "type": "cp",
    "value": -54
  },
  "secondBest": {
    "lines": [
      "f8e8",
      "f4g5",
      "g4f3",
      "g2f3",
      "c6e5",
      "d3b3",
      "h7h6"
    ],
    "eval": {
      "type": "cp",
      "value": -44
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 48
  },
  "bestMove": "Be3",
  "secondBest": {
    "lines": [
      "c4b5",
      "c6b4",
      "d3d1",
      "d6d5",
      "e4e5",
      "f6e4",
      "h2h3"
    ],
    "eval": {
      "type": "cp",
      "value": -5
    }
  },
  "hangingPieces": {
    "w": [],
    "b": []
  }
},
};

const move_10_b: GameMove = {
  analyzerMoveType: "good",
  expectedMoveType: "good",
  expectedComment: null,
  moveIndex: 19,
  position: {
  "color": "b",
  "san": "Bxf3",
  "before": "r2q1rk1/ppp2ppp/1bnp1n2/8/2BPPBb1/3Q1N2/PPP1N1PP/R4RK1 b - - 4 10",
  "after": "r2q1rk1/ppp2ppp/1bnp1n2/8/2BPPB2/3Q1b2/PPP1N1PP/R4RK1 w - - 0 11",
  "from": "g4",
  "to": "f3",
  "piece": "b",
  "flags": "c",
  "lan": "g4f3",
  "isBigPawn": false,
  "isCapture": true,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Rxf3",
  "lines": [
    "Rxf3",
    "Qe7",
    "c3",
    "Qxe4",
    "Qxe4",
    "Nxe4",
    "Raf1",
    "Rad8",
    "Ng3",
    "d5",
    "Bb3",
    "Na5",
    "Nxe4",
    "dxe4"
  ],
  "eval": {
    "type": "cp",
    "value": -20
  },
  "secondBest": {
    "lines": [
      "g2f3",
      "d6d5",
      "e4d5",
      "f6d5",
      "c4d5",
      "d8d5",
      "c2c3",
      "a8e8",
      "a2a4",
      "d5b3"
    ],
    "eval": {
      "type": "cp",
      "value": -49
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": -54
  },
  "bestMove": "Qe8",
  "secondBest": {
    "lines": [
      "f8e8",
      "f4g5",
      "g4f3",
      "g2f3",
      "c6e5",
      "d3b3",
      "h7h6"
    ],
    "eval": {
      "type": "cp",
      "value": -44
    }
  },
  "hangingPieces": {
    "b": [],
    "w": []
  }
},
};

const move_11_w: GameMove = {
  analyzerMoveType: "best",
  expectedMoveType: "best",
  expectedComment: null,
  moveIndex: 20,
  position: {
  "color": "w",
  "san": "Rxf3",
  "before": "r2q1rk1/ppp2ppp/1bnp1n2/8/2BPPB2/3Q1b2/PPP1N1PP/R4RK1 w - - 0 11",
  "after": "r2q1rk1/ppp2ppp/1bnp1n2/8/2BPPB2/3Q1R2/PPP1N1PP/R5K1 b - - 0 11",
  "from": "f1",
  "to": "f3",
  "piece": "r",
  "flags": "c",
  "lan": "f1f3",
  "isBigPawn": false,
  "isCapture": true,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Qe7",
  "lines": [
    "Qe7",
    "c3",
    "Qxe4",
    "Qxe4",
    "Nxe4",
    "a4",
    "Rae8",
    "Kf1",
    "Kh8",
    "Ng3",
    "f5"
  ],
  "eval": {
    "type": "cp",
    "value": -26
  },
  "secondBest": {
    "lines": [
      "d8e8",
      "c2c3",
      "e8e4",
      "d3e4",
      "f6e4",
      "a2a4",
      "a8e8",
      "g1f1",
      "a7a5",
      "e2g3"
    ],
    "eval": {
      "type": "cp",
      "value": -25
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": -20
  },
  "bestMove": "Rxf3",
  "secondBest": {
    "lines": [
      "g2f3",
      "d6d5",
      "e4d5",
      "f6d5",
      "c4d5",
      "d8d5",
      "c2c3",
      "a8e8",
      "a2a4",
      "d5b3"
    ],
    "eval": {
      "type": "cp",
      "value": -49
    }
  },
  "hangingPieces": {
    "w": [
      "e4"
    ],
    "b": []
  }
},
};

const move_11_b: GameMove = {
  analyzerMoveType: "inaccuracy",
  expectedMoveType: "inaccuracy",
  expectedComment: null,
  moveIndex: 21,
  position: {
  "color": "b",
  "san": "d5",
  "before": "r2q1rk1/ppp2ppp/1bnp1n2/8/2BPPB2/3Q1R2/PPP1N1PP/R5K1 b - - 0 11",
  "after": "r2q1rk1/ppp2ppp/1bn2n2/3p4/2BPPB2/3Q1R2/PPP1N1PP/R5K1 w - - 0 12",
  "from": "d6",
  "to": "d5",
  "piece": "p",
  "flags": "n",
  "lan": "d6d5",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "exd5",
  "lines": [
    "exd5",
    "Nxd5",
    "Bg3",
    "Na5",
    "Bxd5",
    "Qxd5",
    "b3",
    "Rae8",
    "c4",
    "Qe4",
    "Qxe4",
    "Rxe4"
  ],
  "eval": {
    "type": "cp",
    "value": 75
  },
  "secondBest": {
    "lines": [
      "c4d5",
      "c6b4",
      "d3d2",
      "b4d5",
      "e4d5",
      "d8d5",
      "a1c1",
      "c7c6",
      "c2c4",
      "d5a5"
    ],
    "eval": {
      "type": "cp",
      "value": -7
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": -26
  },
  "bestMove": "Qe7",
  "secondBest": {
    "lines": [
      "d8e8",
      "c2c3",
      "e8e4",
      "d3e4",
      "f6e4",
      "a2a4",
      "a8e8",
      "g1f1",
      "a7a5",
      "e2g3"
    ],
    "eval": {
      "type": "cp",
      "value": -25
    }
  },
  "hangingPieces": {
    "b": [],
    "w": []
  }
},
};

const move_12_w: GameMove = {
  analyzerMoveType: "best",
  expectedMoveType: "best",
  expectedComment: null,
  moveIndex: 22,
  position: {
  "color": "w",
  "san": "exd5",
  "before": "r2q1rk1/ppp2ppp/1bn2n2/3p4/2BPPB2/3Q1R2/PPP1N1PP/R5K1 w - - 0 12",
  "after": "r2q1rk1/ppp2ppp/1bn2n2/3P4/2BP1B2/3Q1R2/PPP1N1PP/R5K1 b - - 0 12",
  "from": "e4",
  "to": "d5",
  "piece": "p",
  "flags": "c",
  "lan": "e4d5",
  "isBigPawn": false,
  "isCapture": true,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Nxd5",
  "lines": [
    "Nxd5",
    "Bg3",
    "Na5",
    "Bxd5",
    "Qxd5",
    "b3",
    "Nc6",
    "Bf2",
    "Rfe8",
    "c3",
    "Qe4",
    "Qxe4",
    "Rxe4",
    "Kf1",
    "Rd8",
    "a4",
    "Ree8"
  ],
  "eval": {
    "type": "cp",
    "value": 71
  },
  "secondBest": {
    "lines": [
      "c6b4",
      "d3f5",
      "g7g6",
      "f5h3",
      "b4c2",
      "a1d1",
      "f6d5",
      "f4h6",
      "f8e8",
      "g1h1",
      "e8e2",
      "c4e2",
      "c2d4",
      "f3f2",
      "c7c6"
    ],
    "eval": {
      "type": "cp",
      "value": 90
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 75
  },
  "bestMove": "exd5",
  "secondBest": {
    "lines": [
      "c4d5",
      "c6b4",
      "d3d2",
      "b4d5",
      "e4d5",
      "d8d5",
      "a1c1",
      "c7c6",
      "c2c4",
      "d5a5"
    ],
    "eval": {
      "type": "cp",
      "value": -7
    }
  },
  "hangingPieces": {
    "w": [
      "e4"
    ],
    "b": []
  }
},
};

const move_12_b: GameMove = {
  analyzerMoveType: "best",
  expectedMoveType: "best",
  expectedComment: null,
  moveIndex: 23,
  position: {
  "color": "b",
  "san": "Nxd5",
  "before": "r2q1rk1/ppp2ppp/1bn2n2/3P4/2BP1B2/3Q1R2/PPP1N1PP/R5K1 b - - 0 12",
  "after": "r2q1rk1/ppp2ppp/1bn5/3n4/2BP1B2/3Q1R2/PPP1N1PP/R5K1 w - - 0 13",
  "from": "f6",
  "to": "d5",
  "piece": "n",
  "flags": "c",
  "lan": "f6d5",
  "isBigPawn": false,
  "isCapture": true,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Kh1",
  "lines": [
    "Kh1",
    "Nxf4",
    "Rxf4",
    "Na5",
    "Rxf7",
    "Nxc4",
    "Rxf8+",
    "Qxf8",
    "Qxc4+",
    "Qf7",
    "Qxf7+",
    "Kxf7"
  ],
  "eval": {
    "type": "cp",
    "value": 69
  },
  "secondBest": {
    "lines": [
      "f4g3",
      "c6a5",
      "c4d5",
      "d8d5",
      "b2b3",
      "a5c6",
      "g3f2",
      "f8e8",
      "c2c4",
      "d5e4",
      "g1f1",
      "e4d3",
      "f3d3",
      "c6b4",
      "d3f3",
      "c7c6"
    ],
    "eval": {
      "type": "cp",
      "value": 67
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 71
  },
  "bestMove": "Nxd5",
  "secondBest": {
    "lines": [
      "c6b4",
      "d3f5",
      "g7g6",
      "f5h3",
      "b4c2",
      "a1d1",
      "f6d5",
      "f4h6",
      "f8e8",
      "g1h1",
      "e8e2",
      "c4e2",
      "c2d4",
      "f3f2",
      "c7c6"
    ],
    "eval": {
      "type": "cp",
      "value": 90
    }
  },
  "hangingPieces": {
    "b": [
      "c6"
    ],
    "w": [
      "d5"
    ]
  }
},
};

const move_13_w: GameMove = {
  analyzerMoveType: "good",
  expectedMoveType: "good",
  expectedComment: null,
  moveIndex: 24,
  position: {
  "color": "w",
  "san": "Bg3",
  "before": "r2q1rk1/ppp2ppp/1bn5/3n4/2BP1B2/3Q1R2/PPP1N1PP/R5K1 w - - 0 13",
  "after": "r2q1rk1/ppp2ppp/1bn5/3n4/2BP4/3Q1RB1/PPP1N1PP/R5K1 b - - 1 13",
  "from": "f4",
  "to": "g3",
  "piece": "b",
  "flags": "n",
  "lan": "f4g3",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Na5",
  "lines": [
    "Na5",
    "Bxd5",
    "Qxd5",
    "b3",
    "Nc6",
    "Bf2",
    "Rad8",
    "c4",
    "Qd6",
    "Rd1",
    "Rfe8",
    "Kh1",
    "Bxd4",
    "Bxd4",
    "Qd7"
  ],
  "eval": {
    "type": "cp",
    "value": 66
  },
  "secondBest": {
    "lines": [
      "d8d7",
      "g3f2",
      "f8e8",
      "a1f1"
    ],
    "eval": {
      "type": "cp",
      "value": 138
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 69
  },
  "bestMove": "Kh1",
  "secondBest": {
    "lines": [
      "f4g3",
      "c6a5",
      "c4d5",
      "d8d5",
      "b2b3",
      "a5c6",
      "g3f2",
      "f8e8",
      "c2c4",
      "d5e4",
      "g1f1",
      "e4d3",
      "f3d3",
      "c6b4",
      "d3f3",
      "c7c6"
    ],
    "eval": {
      "type": "cp",
      "value": 67
    }
  },
  "hangingPieces": {
    "w": [],
    "b": []
  }
},
};

const move_13_b: GameMove = {
  analyzerMoveType: "inaccuracy",
  expectedMoveType: "inaccuracy",
  expectedComment: null,
  moveIndex: 25,
  position: {
  "color": "b",
  "san": "Ndb4",
  "before": "r2q1rk1/ppp2ppp/1bn5/3n4/2BP4/3Q1RB1/PPP1N1PP/R5K1 b - - 1 13",
  "after": "r2q1rk1/ppp2ppp/1bn5/8/1nBP4/3Q1RB1/PPP1N1PP/R5K1 w - - 2 14",
  "from": "d5",
  "to": "b4",
  "piece": "n",
  "flags": "n",
  "lan": "d5b4",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Qb3",
  "lines": [
    "Qb3",
    "Nxd4",
    "Nxd4",
    "Qxd4+",
    "Kh1",
    "Nc6",
    "Bxf7+",
    "Kh8",
    "Raf1",
    "Qc5"
  ],
  "eval": {
    "type": "cp",
    "value": 170
  },
  "secondBest": {
    "lines": [
      "d3f5",
      "c6d4",
      "c4f7",
      "g8h8",
      "e2d4",
      "d8d4",
      "g1h1",
      "b4c6",
      "c2c3",
      "d4c5",
      "f5c5",
      "b6c5",
      "g3c7"
    ],
    "eval": {
      "type": "cp",
      "value": 135
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 66
  },
  "bestMove": "Na5",
  "secondBest": {
    "lines": [
      "d8d7",
      "g3f2",
      "f8e8",
      "a1f1"
    ],
    "eval": {
      "type": "cp",
      "value": 138
    }
  },
  "hangingPieces": {
    "b": [],
    "w": []
  }
},
};

const move_14_w: GameMove = {
  analyzerMoveType: "best",
  expectedMoveType: "best",
  expectedComment: null,
  moveIndex: 26,
  position: {
  "color": "w",
  "san": "Qb3",
  "before": "r2q1rk1/ppp2ppp/1bn5/8/1nBP4/3Q1RB1/PPP1N1PP/R5K1 w - - 2 14",
  "after": "r2q1rk1/ppp2ppp/1bn5/8/1nBP4/1Q3RB1/PPP1N1PP/R5K1 b - - 3 14",
  "from": "d3",
  "to": "b3",
  "piece": "q",
  "flags": "n",
  "lan": "d3b3",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Qe7",
  "lines": [
    "Qe7",
    "c3",
    "Na5",
    "Rxf7",
    "Rxf7",
    "Bxf7+",
    "Qxf7",
    "Qxb4",
    "Rf8",
    "Re1",
    "Re8",
    "h3",
    "Nc4"
  ],
  "eval": {
    "type": "cp",
    "value": 111
  },
  "secondBest": {
    "lines": [
      "c6d4",
      "e2d4",
      "d8d4",
      "g1h1",
      "b4c6",
      "c2c3",
      "d4c5",
      "c4f7",
      "g8h8",
      "a1e1",
      "c6d8",
      "f7e8",
      "f8f3",
      "g2f3",
      "c5f5",
      "h1g2"
    ],
    "eval": {
      "type": "cp",
      "value": 153
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 170
  },
  "bestMove": "Qb3",
  "secondBest": {
    "lines": [
      "d3f5",
      "c6d4",
      "c4f7",
      "g8h8",
      "e2d4",
      "d8d4",
      "g1h1",
      "b4c6",
      "c2c3",
      "d4c5",
      "f5c5",
      "b6c5",
      "g3c7"
    ],
    "eval": {
      "type": "cp",
      "value": 135
    }
  },
  "hangingPieces": {
    "w": [
      "d3",
      "d4"
    ],
    "b": []
  }
},
};

const move_14_b: GameMove = {
  analyzerMoveType: "mistake",
  expectedMoveType: "mistake",
  expectedComment: null,
  moveIndex: 27,
  position: {
  "color": "b",
  "san": "Na6",
  "before": "r2q1rk1/ppp2ppp/1bn5/8/1nBP4/1Q3RB1/PPP1N1PP/R5K1 b - - 3 14",
  "after": "r2q1rk1/ppp2ppp/nbn5/8/2BP4/1Q3RB1/PPP1N1PP/R5K1 w - - 4 15",
  "from": "b4",
  "to": "a6",
  "piece": "n",
  "flags": "n",
  "lan": "b4a6",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Rxf7",
  "lines": [
    "Rxf7",
    "Rxf7",
    "Bxf7+",
    "Kh8",
    "c3",
    "Qe7",
    "Qe6",
    "Rf8",
    "Qxe7",
    "Nxe7",
    "Rf1"
  ],
  "eval": {
    "type": "cp",
    "value": 317
  },
  "secondBest": {
    "lines": [
      "c2c3",
      "c6a5",
      "c4f7",
      "g8h8",
      "b3c2",
      "c7c5",
      "d4d5"
    ],
    "eval": {
      "type": "cp",
      "value": 302
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 111
  },
  "bestMove": "Qe7",
  "secondBest": {
    "lines": [
      "c6d4",
      "e2d4",
      "d8d4",
      "g1h1",
      "b4c6",
      "c2c3",
      "d4c5",
      "c4f7",
      "g8h8",
      "a1e1",
      "c6d8",
      "f7e8",
      "f8f3",
      "g2f3",
      "c5f5",
      "h1g2"
    ],
    "eval": {
      "type": "cp",
      "value": 153
    }
  },
  "hangingPieces": {
    "b": [
      "f7"
    ],
    "w": [
      "d4"
    ]
  }
},
};

const move_15_w: GameMove = {
  analyzerMoveType: "good",
  expectedMoveType: "good",
  expectedComment: null,
  moveIndex: 28,
  position: {
  "color": "w",
  "san": "c3",
  "before": "r2q1rk1/ppp2ppp/nbn5/8/2BP4/1Q3RB1/PPP1N1PP/R5K1 w - - 4 15",
  "after": "r2q1rk1/ppp2ppp/nbn5/8/2BP4/1QP2RB1/PP2N1PP/R5K1 b - - 0 15",
  "from": "c2",
  "to": "c3",
  "piece": "p",
  "flags": "n",
  "lan": "c2c3",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Kh8",
  "lines": [
    "Kh8",
    "Bxf7",
    "Na5",
    "Qe6",
    "c5",
    "Kh1",
    "cxd4",
    "Qh3",
    "dxc3",
    "Nxc3"
  ],
  "eval": {
    "type": "cp",
    "value": 294
  },
  "secondBest": {
    "lines": [
      "c6a5",
      "c4f7",
      "g8h8",
      "b3e6",
      "c7c5",
      "e6h3",
      "c5d4",
      "g1h1",
      "d4c3",
      "a1f1",
      "c3b2"
    ],
    "eval": {
      "type": "cp",
      "value": 306
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 317
  },
  "bestMove": "Rxf7",
  "secondBest": {
    "lines": [
      "c2c3",
      "c6a5",
      "c4f7",
      "g8h8",
      "b3c2",
      "c7c5",
      "d4d5"
    ],
    "eval": {
      "type": "cp",
      "value": 302
    }
  },
  "hangingPieces": {
    "w": [
      "d4"
    ],
    "b": [
      "f7"
    ]
  }
},
};

const move_15_b: GameMove = {
  analyzerMoveType: "inaccuracy",
  expectedMoveType: "inaccuracy",
  expectedComment: null,
  moveIndex: 29,
  position: {
  "color": "b",
  "san": "Nab8",
  "before": "r2q1rk1/ppp2ppp/nbn5/8/2BP4/1QP2RB1/PP2N1PP/R5K1 b - - 0 15",
  "after": "rn1q1rk1/ppp2ppp/1bn5/8/2BP4/1QP2RB1/PP2N1PP/R5K1 w - - 1 16",
  "from": "a6",
  "to": "b8",
  "piece": "n",
  "flags": "n",
  "lan": "a6b8",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Raf1",
  "lines": [
    "Raf1",
    "Kh8",
    "Qb5",
    "f6",
    "Bd3",
    "Qe8",
    "Nf4"
  ],
  "eval": {
    "type": "cp",
    "value": 357
  },
  "secondBest": {
    "lines": [
      "f3f7",
      "f8f7",
      "a1f1",
      "g8h8",
      "c4f7",
      "b8d7",
      "b3e6",
      "d8e7",
      "e2f4",
      "d7f6",
      "e6e7",
      "c6e7",
      "f4e6"
    ],
    "eval": {
      "type": "cp",
      "value": 337
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 294
  },
  "bestMove": "Kh8",
  "secondBest": {
    "lines": [
      "c6a5",
      "c4f7",
      "g8h8",
      "b3e6",
      "c7c5",
      "e6h3",
      "c5d4",
      "g1h1",
      "d4c3",
      "a1f1",
      "c3b2"
    ],
    "eval": {
      "type": "cp",
      "value": 306
    }
  },
  "hangingPieces": {
    "b": [
      "f7"
    ],
    "w": []
  }
},
};

const move_16_w: GameMove = {
  analyzerMoveType: "good",
  expectedMoveType: "good",
  expectedComment: null,
  moveIndex: 30,
  position: {
  "color": "w",
  "san": "Bxf7+",
  "before": "rn1q1rk1/ppp2ppp/1bn5/8/2BP4/1QP2RB1/PP2N1PP/R5K1 w - - 1 16",
  "after": "rn1q1rk1/ppp2Bpp/1bn5/8/3P4/1QP2RB1/PP2N1PP/R5K1 b - - 0 16",
  "from": "c4",
  "to": "f7",
  "piece": "b",
  "flags": "c",
  "lan": "c4f7",
  "isBigPawn": false,
  "isCapture": true,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Kh8",
  "lines": [
    "Kh8",
    "a4",
    "Nd7",
    "Qe6",
    "Nf6",
    "Bh4",
    "Qd6",
    "Qxd6"
  ],
  "eval": {
    "type": "cp",
    "value": 324
  },
  "secondBest": {
    "lines": [
      "f8f7",
      "b3f7",
      "g8h8",
      "f7f8",
      "d8f8",
      "f3f8"
    ],
    "eval": {
      "type": "mate",
      "value": 3
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 357
  },
  "bestMove": "Raf1",
  "secondBest": {
    "lines": [
      "f3f7",
      "f8f7",
      "a1f1",
      "g8h8",
      "c4f7",
      "b8d7",
      "b3e6",
      "d8e7",
      "e2f4",
      "d7f6",
      "e6e7",
      "c6e7",
      "f4e6"
    ],
    "eval": {
      "type": "cp",
      "value": 337
    }
  },
  "hangingPieces": {
    "w": [],
    "b": [
      "f7"
    ]
  }
},
};

const move_16_b: GameMove = {
  analyzerMoveType: "best",
  expectedMoveType: "best",
  expectedComment: null,
  moveIndex: 31,
  position: {
  "color": "b",
  "san": "Kh8",
  "before": "rn1q1rk1/ppp2Bpp/1bn5/8/3P4/1QP2RB1/PP2N1PP/R5K1 b - - 0 16",
  "after": "rn1q1r1k/ppp2Bpp/1bn5/8/3P4/1QP2RB1/PP2N1PP/R5K1 w - - 1 17",
  "from": "g8",
  "to": "h8",
  "piece": "k",
  "flags": "n",
  "lan": "g8h8",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Qe6",
  "lines": [
    "Qe6",
    "Nd7",
    "a4",
    "Nf6",
    "Re1",
    "Qe7",
    "Qxe7",
    "Nxe7",
    "Bc4",
    "Ne4"
  ],
  "eval": {
    "type": "cp",
    "value": 329
  },
  "secondBest": {
    "lines": [
      "a2a4",
      "b8d7",
      "b3e6",
      "d7f6",
      "a1f1",
      "d8e7",
      "e6e7",
      "c6e7",
      "f7a2",
      "a8e8"
    ],
    "eval": {
      "type": "cp",
      "value": 325
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 324
  },
  "bestMove": "Kh8",
  "secondBest": {
    "lines": [
      "f8f7",
      "b3f7",
      "g8h8",
      "f7f8",
      "d8f8",
      "f3f8"
    ],
    "eval": {
      "type": "mate",
      "value": 3
    }
  },
  "hangingPieces": {
    "b": [],
    "w": []
  }
},
};

const move_17_w: GameMove = {
  analyzerMoveType: "good",
  expectedMoveType: "good",
  expectedComment: null,
  moveIndex: 32,
  position: {
  "color": "w",
  "san": "Raf1",
  "before": "rn1q1r1k/ppp2Bpp/1bn5/8/3P4/1QP2RB1/PP2N1PP/R5K1 w - - 1 17",
  "after": "rn1q1r1k/ppp2Bpp/1bn5/8/3P4/1QP2RB1/PP2N1PP/5RK1 b - - 2 17",
  "from": "a1",
  "to": "f1",
  "piece": "r",
  "flags": "n",
  "lan": "a1f1",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Nd7",
  "lines": [
    "Nd7",
    "Qb5",
    "Qe7",
    "Bb3",
    "Rxf3",
    "Rxf3",
    "Nf6"
  ],
  "eval": {
    "type": "cp",
    "value": 321
  },
  "secondBest": {
    "lines": [
      "d8e7",
      "b3d1",
      "b8d7",
      "f7b3",
      "f8f3",
      "f1f3"
    ],
    "eval": {
      "type": "cp",
      "value": 335
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 329
  },
  "bestMove": "Qe6",
  "secondBest": {
    "lines": [
      "a2a4",
      "b8d7",
      "b3e6",
      "d7f6",
      "a1f1",
      "d8e7",
      "e6e7",
      "c6e7",
      "f7a2",
      "a8e8"
    ],
    "eval": {
      "type": "cp",
      "value": 325
    }
  },
  "hangingPieces": {
    "w": [],
    "b": []
  }
},
};

const move_17_b: GameMove = {
  analyzerMoveType: "best",
  expectedMoveType: "best",
  expectedComment: null,
  moveIndex: 33,
  position: {
  "color": "b",
  "san": "Nd7",
  "before": "rn1q1r1k/ppp2Bpp/1bn5/8/3P4/1QP2RB1/PP2N1PP/5RK1 b - - 2 17",
  "after": "r2q1r1k/pppn1Bpp/1bn5/8/3P4/1QP2RB1/PP2N1PP/5RK1 w - - 3 18",
  "from": "b8",
  "to": "d7",
  "piece": "n",
  "flags": "n",
  "lan": "b8d7",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Kh1",
  "lines": [
    "Kh1",
    "Qe7",
    "Qd1",
    "Nf6",
    "Bc4",
    "Na5",
    "Bd3",
    "c5"
  ],
  "eval": {
    "type": "cp",
    "value": 342
  },
  "secondBest": {
    "lines": [
      "b3e6",
      "d8e7",
      "e6e7",
      "c6e7",
      "a2a4",
      "c7c5",
      "a4a5",
      "b6a5",
      "g3d6",
      "d7f6"
    ],
    "eval": {
      "type": "cp",
      "value": 312
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 321
  },
  "bestMove": "Nd7",
  "secondBest": {
    "lines": [
      "d8e7",
      "b3d1",
      "b8d7",
      "f7b3",
      "f8f3",
      "f1f3"
    ],
    "eval": {
      "type": "cp",
      "value": 335
    }
  },
  "hangingPieces": {
    "b": [],
    "w": []
  }
},
};

const move_18_w: GameMove = {
  analyzerMoveType: "good",
  expectedMoveType: "good",
  expectedComment: null,
  moveIndex: 34,
  position: {
  "color": "w",
  "san": "Bh5",
  "before": "r2q1r1k/pppn1Bpp/1bn5/8/3P4/1QP2RB1/PP2N1PP/5RK1 w - - 3 18",
  "after": "r2q1r1k/pppn2pp/1bn5/7B/3P4/1QP2RB1/PP2N1PP/5RK1 b - - 4 18",
  "from": "f7",
  "to": "h5",
  "piece": "b",
  "flags": "n",
  "lan": "f7h5",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Nf6",
  "lines": [
    "Nf6",
    "Kh1",
    "Qe7",
    "Qb5",
    "Nxh5",
    "Qxh5",
    "Rxf3",
    "Qxf3",
    "Re8",
    "Nf4",
    "Qe4"
  ],
  "eval": {
    "type": "cp",
    "value": 316
  },
  "secondBest": {
    "lines": [
      "d8e7",
      "g1h1",
      "d7f6",
      "b3b5",
      "f6h5",
      "b5h5",
      "f8f3",
      "h5f3",
      "a8e8",
      "e2f4",
      "e7e4"
    ],
    "eval": {
      "type": "cp",
      "value": 316
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 342
  },
  "bestMove": "Kh1",
  "secondBest": {
    "lines": [
      "b3e6",
      "d8e7",
      "e6e7",
      "c6e7",
      "a2a4",
      "c7c5",
      "a4a5",
      "b6a5",
      "g3d6",
      "d7f6"
    ],
    "eval": {
      "type": "cp",
      "value": 312
    }
  },
  "hangingPieces": {
    "w": [],
    "b": []
  }
},
};

const move_18_b: GameMove = {
  analyzerMoveType: "best",
  expectedMoveType: "best",
  expectedComment: null,
  moveIndex: 35,
  position: {
  "color": "b",
  "san": "Nf6",
  "before": "r2q1r1k/pppn2pp/1bn5/7B/3P4/1QP2RB1/PP2N1PP/5RK1 b - - 4 18",
  "after": "r2q1r1k/ppp3pp/1bn2n2/7B/3P4/1QP2RB1/PP2N1PP/5RK1 w - - 5 19",
  "from": "d7",
  "to": "f6",
  "piece": "n",
  "flags": "n",
  "lan": "d7f6",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Bh4",
  "lines": [
    "Bh4",
    "Qe7",
    "Ng3",
    "Ne5",
    "R3f2",
    "Qd6",
    "Nf5",
    "Nxh5",
    "Nxd6"
  ],
  "eval": {
    "type": "cp",
    "value": 289
  },
  "secondBest": {
    "lines": [
      "g1h1",
      "d8e7",
      "e2f4",
      "b6d4",
      "f4e6",
      "c6a5"
    ],
    "eval": {
      "type": "cp",
      "value": 280
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 316
  },
  "bestMove": "Nf6",
  "secondBest": {
    "lines": [
      "d8e7",
      "g1h1",
      "d7f6",
      "b3b5",
      "f6h5",
      "b5h5",
      "f8f3",
      "h5f3",
      "a8e8",
      "e2f4",
      "e7e4"
    ],
    "eval": {
      "type": "cp",
      "value": 316
    }
  },
  "hangingPieces": {
    "b": [],
    "w": []
  }
},
};

const move_19_w: GameMove = {
  analyzerMoveType: "inaccuracy",
  expectedMoveType: "inaccuracy",
  expectedComment: null,
  moveIndex: 36,
  position: {
  "color": "w",
  "san": "Qa3",
  "before": "r2q1r1k/ppp3pp/1bn2n2/7B/3P4/1QP2RB1/PP2N1PP/5RK1 w - - 5 19",
  "after": "r2q1r1k/ppp3pp/1bn2n2/7B/3P4/Q1P2RB1/PP2N1PP/5RK1 b - - 6 19",
  "from": "b3",
  "to": "a3",
  "piece": "q",
  "flags": "n",
  "lan": "b3a3",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Na5",
  "lines": [
    "Na5",
    "Qb4",
    "Rc8",
    "Qa4",
    "c5",
    "d5",
    "c4+",
    "Kh1"
  ],
  "eval": {
    "type": "cp",
    "value": 205
  },
  "secondBest": {
    "lines": [
      "d8d5",
      "f3f5",
      "d5e6",
      "a3b3",
      "e6e3",
      "g3f2"
    ],
    "eval": {
      "type": "cp",
      "value": 212
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 289
  },
  "bestMove": "Bh4",
  "secondBest": {
    "lines": [
      "g1h1",
      "d8e7",
      "e2f4",
      "b6d4",
      "f4e6",
      "c6a5"
    ],
    "eval": {
      "type": "cp",
      "value": 280
    }
  },
  "hangingPieces": {
    "w": [],
    "b": []
  }
},
};

const move_19_b: GameMove = {
  analyzerMoveType: "inaccuracy",
  expectedMoveType: "inaccuracy",
  expectedComment: null,
  moveIndex: 37,
  position: {
  "color": "b",
  "san": "Ne7",
  "before": "r2q1r1k/ppp3pp/1bn2n2/7B/3P4/Q1P2RB1/PP2N1PP/5RK1 b - - 6 19",
  "after": "r2q1r1k/ppp1n1pp/1b3n2/7B/3P4/Q1P2RB1/PP2N1PP/5RK1 w - - 7 20",
  "from": "c6",
  "to": "e7",
  "piece": "n",
  "flags": "n",
  "lan": "c6e7",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Be5",
  "lines": [
    "Be5",
    "c5",
    "dxc5",
    "Bc7",
    "Bxf6",
    "gxf6",
    "Rh3",
    "Qd5",
    "Bf3"
  ],
  "eval": {
    "type": "cp",
    "value": 276
  },
  "secondBest": {
    "lines": [
      "g1h1",
      "d8d7",
      "g3e5",
      "c7c5",
      "d4c5",
      "b6c7",
      "e5f6",
      "f8f6",
      "f3f6"
    ],
    "eval": {
      "type": "cp",
      "value": 258
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 205
  },
  "bestMove": "Na5",
  "secondBest": {
    "lines": [
      "d8d5",
      "f3f5",
      "d5e6",
      "a3b3",
      "e6e3",
      "g3f2"
    ],
    "eval": {
      "type": "cp",
      "value": 212
    }
  },
  "hangingPieces": {
    "b": [],
    "w": []
  }
},
};

const move_20_w: GameMove = {
  analyzerMoveType: "good",
  expectedMoveType: "good",
  expectedComment: null,
  moveIndex: 38,
  position: {
  "color": "w",
  "san": "Bh4",
  "before": "r2q1r1k/ppp1n1pp/1b3n2/7B/3P4/Q1P2RB1/PP2N1PP/5RK1 w - - 7 20",
  "after": "r2q1r1k/ppp1n1pp/1b3n2/7B/3P3B/Q1P2R2/PP2N1PP/5RK1 b - - 8 20",
  "from": "g3",
  "to": "h4",
  "piece": "b",
  "flags": "n",
  "lan": "g3h4",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Neg8",
  "lines": [
    "Neg8",
    "Qb4",
    "Qd5",
    "Nf4",
    "Qxa2"
  ],
  "eval": {
    "type": "cp",
    "value": 238
  },
  "secondBest": {
    "lines": [
      "d8d7",
      "h4f6",
      "g7f6",
      "a3b4",
      "c7c6",
      "b4c4",
      "b6c7"
    ],
    "eval": {
      "type": "cp",
      "value": 248
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 276
  },
  "bestMove": "Be5",
  "secondBest": {
    "lines": [
      "g1h1",
      "d8d7",
      "g3e5",
      "c7c5",
      "d4c5",
      "b6c7",
      "e5f6",
      "f8f6",
      "f3f6"
    ],
    "eval": {
      "type": "cp",
      "value": 258
    }
  },
  "hangingPieces": {
    "w": [],
    "b": []
  }
},
};

const move_20_b: GameMove = {
  analyzerMoveType: "inaccuracy",
  expectedMoveType: "inaccuracy",
  expectedComment: null,
  moveIndex: 39,
  position: {
  "color": "b",
  "san": "Ned5",
  "before": "r2q1r1k/ppp1n1pp/1b3n2/7B/3P3B/Q1P2R2/PP2N1PP/5RK1 b - - 8 20",
  "after": "r2q1r1k/ppp3pp/1b3n2/3n3B/3P3B/Q1P2R2/PP2N1PP/5RK1 w - - 9 21",
  "from": "e7",
  "to": "d5",
  "piece": "n",
  "flags": "n",
  "lan": "e7d5",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "c4",
  "lines": [
    "c4",
    "Qe7",
    "Qxe7",
    "Nxe7",
    "c5",
    "Ba5",
    "Rxf6",
    "gxf6",
    "Bxf6+",
    "Rxf6",
    "Rxf6",
    "Nc6",
    "Bf3"
  ],
  "eval": {
    "type": "cp",
    "value": 319
  },
  "secondBest": {
    "lines": [
      "g1h1",
      "d5e3",
      "f3e3",
      "f6h5",
      "f1f3",
      "f8f3",
      "e3f3"
    ],
    "eval": {
      "type": "cp",
      "value": 273
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 238
  },
  "bestMove": "Neg8",
  "secondBest": {
    "lines": [
      "d8d7",
      "h4f6",
      "g7f6",
      "a3b4",
      "c7c6",
      "b4c4",
      "b6c7"
    ],
    "eval": {
      "type": "cp",
      "value": 248
    }
  },
  "hangingPieces": {
    "b": [],
    "w": []
  }
},
};

const move_21_w: GameMove = {
  analyzerMoveType: "inaccuracy",
  expectedMoveType: "inaccuracy",
  expectedComment: null,
  moveIndex: 40,
  position: {
  "color": "w",
  "san": "Bg4",
  "before": "r2q1r1k/ppp3pp/1b3n2/3n3B/3P3B/Q1P2R2/PP2N1PP/5RK1 w - - 9 21",
  "after": "r2q1r1k/ppp3pp/1b3n2/3n4/3P2BB/Q1P2R2/PP2N1PP/5RK1 b - - 10 21",
  "from": "h5",
  "to": "g4",
  "piece": "b",
  "flags": "n",
  "lan": "h5g4",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Qe8",
  "lines": [
    "Qe8",
    "Ng3",
    "c6",
    "Bh3",
    "h6",
    "Nf5",
    "g5",
    "Re1"
  ],
  "eval": {
    "type": "cp",
    "value": 204
  },
  "secondBest": {
    "lines": [
      "c7c6",
      "c3c4",
      "f8e8",
      "c4d5",
      "e8e2"
    ],
    "eval": {
      "type": "cp",
      "value": 230
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 319
  },
  "bestMove": "c4",
  "secondBest": {
    "lines": [
      "g1h1",
      "d5e3",
      "f3e3",
      "f6h5",
      "f1f3",
      "f8f3",
      "e3f3"
    ],
    "eval": {
      "type": "cp",
      "value": 273
    }
  },
  "hangingPieces": {
    "w": [],
    "b": []
  }
},
};

const move_21_b: GameMove = {
  analyzerMoveType: "best",
  expectedMoveType: "best",
  expectedComment: null,
  moveIndex: 41,
  position: {
  "color": "b",
  "san": "Qe8",
  "before": "r2q1r1k/ppp3pp/1b3n2/3n4/3P2BB/Q1P2R2/PP2N1PP/5RK1 b - - 10 21",
  "after": "r3qr1k/ppp3pp/1b3n2/3n4/3P2BB/Q1P2R2/PP2N1PP/5RK1 w - - 11 22",
  "from": "d8",
  "to": "e8",
  "piece": "q",
  "flags": "n",
  "lan": "d8e8",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Ng3",
  "lines": [
    "Ng3",
    "Rg8",
    "Bxf6",
    "Nxf6",
    "Bh3",
    "Rd8",
    "b4"
  ],
  "eval": {
    "type": "cp",
    "value": 208
  },
  "secondBest": {
    "lines": [
      "e2f4",
      "d5f4",
      "f3f4",
      "c7c5",
      "g1h1",
      "c5d4",
      "g4f3",
      "d4c3",
      "f3b7",
      "a8d8",
      "a3c3"
    ],
    "eval": {
      "type": "cp",
      "value": 119
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 204
  },
  "bestMove": "Qe8",
  "secondBest": {
    "lines": [
      "c7c6",
      "c3c4",
      "f8e8",
      "c4d5",
      "e8e2"
    ],
    "eval": {
      "type": "cp",
      "value": 230
    }
  },
  "hangingPieces": {
    "b": [],
    "w": []
  }
},
};

const move_22_w: GameMove = {
  analyzerMoveType: "best",
  expectedMoveType: "best",
  expectedComment: null,
  moveIndex: 42,
  position: {
  "color": "w",
  "san": "Ng3",
  "before": "r3qr1k/ppp3pp/1b3n2/3n4/3P2BB/Q1P2R2/PP2N1PP/5RK1 w - - 11 22",
  "after": "r3qr1k/ppp3pp/1b3n2/3n4/3P2BB/Q1P2RN1/PP4PP/5RK1 b - - 12 22",
  "from": "e2",
  "to": "g3",
  "piece": "n",
  "flags": "n",
  "lan": "e2g3",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "h6",
  "lines": [
    "h6",
    "Bh5",
    "Qe6",
    "Bg6",
    "Ne3",
    "Re1",
    "Qg4",
    "Rexe3",
    "Qxg6"
  ],
  "eval": {
    "type": "cp",
    "value": 202
  },
  "secondBest": {
    "lines": [
      "f8g8",
      "h4f6",
      "d5f6",
      "g4h3",
      "c7c5",
      "d4c5",
      "b6c7",
      "a3b4",
      "b7b6",
      "c5b6",
      "a7b6"
    ],
    "eval": {
      "type": "cp",
      "value": 219
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 208
  },
  "bestMove": "Ng3",
  "secondBest": {
    "lines": [
      "e2f4",
      "d5f4",
      "f3f4",
      "c7c5",
      "g1h1",
      "c5d4",
      "g4f3",
      "d4c3",
      "f3b7",
      "a8d8",
      "a3c3"
    ],
    "eval": {
      "type": "cp",
      "value": 119
    }
  },
  "hangingPieces": {
    "w": [
      "e2"
    ],
    "b": []
  }
},
};

const move_22_b: GameMove = {
  analyzerMoveType: "inaccuracy",
  expectedMoveType: "inaccuracy",
  expectedComment: null,
  moveIndex: 43,
  position: {
  "color": "b",
  "san": "Ne3",
  "before": "r3qr1k/ppp3pp/1b3n2/3n4/3P2BB/Q1P2RN1/PP4PP/5RK1 b - - 12 22",
  "after": "r3qr1k/ppp3pp/1b3n2/8/3P2BB/Q1P1nRN1/PP4PP/5RK1 w - - 13 23",
  "from": "d5",
  "to": "e3",
  "piece": "n",
  "flags": "n",
  "lan": "d5e3",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Bh5",
  "lines": [
    "Bh5",
    "g6",
    "Bxg6",
    "hxg6",
    "Bxf6+",
    "Rxf6",
    "Rxf6",
    "Nxf1",
    "Nxf1"
  ],
  "eval": {
    "type": "cp",
    "value": 264
  },
  "secondBest": {
    "lines": [
      "f3f6",
      "g7f6",
      "g4h5",
      "e8e6",
      "f1e1",
      "c7c5",
      "d4d5",
      "e6e5",
      "c3c4",
      "e5d4",
      "a3e3",
      "d4h4"
    ],
    "eval": {
      "type": "cp",
      "value": 60
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 202
  },
  "bestMove": "h6",
  "secondBest": {
    "lines": [
      "f8g8",
      "h4f6",
      "d5f6",
      "g4h3",
      "c7c5",
      "d4c5",
      "b6c7",
      "a3b4",
      "b7b6",
      "c5b6",
      "a7b6"
    ],
    "eval": {
      "type": "cp",
      "value": 219
    }
  },
  "hangingPieces": {
    "b": [],
    "w": []
  }
},
};

const move_23_w: GameMove = {
  analyzerMoveType: "blunder",
  expectedMoveType: "blunder",
  expectedComment: null,
  moveIndex: 44,
  position: {
  "color": "w",
  "san": "Re1",
  "before": "r3qr1k/ppp3pp/1b3n2/8/3P2BB/Q1P1nRN1/PP4PP/5RK1 w - - 13 23",
  "after": "r3qr1k/ppp3pp/1b3n2/8/3P2BB/Q1P1nRN1/PP4PP/4R1K1 b - - 14 23",
  "from": "f1",
  "to": "e1",
  "piece": "r",
  "flags": "n",
  "lan": "f1e1",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Nfxg4",
  "lines": [
    "Nfxg4",
    "Qxf8+",
    "Qxf8",
    "Rxf8+",
    "Rxf8",
    "h3",
    "Nc2",
    "Re2",
    "Nxd4",
    "cxd4",
    "Bxd4+",
    "Kh1",
    "Ne3",
    "Bg5"
  ],
  "eval": {
    "type": "cp",
    "value": -158
  },
  "secondBest": {
    "lines": [
      "b6d4",
      "c3d4",
      "f6g4",
      "e1e3",
      "g4e3",
      "f3e3",
      "e8d7",
      "e3e4",
      "f8e8",
      "h4e7",
      "c7c5",
      "e7c5",
      "e8e4",
      "g3e4",
      "a8e8"
    ],
    "eval": {
      "type": "cp",
      "value": 219
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": 264
  },
  "bestMove": "Bh5",
  "secondBest": {
    "lines": [
      "f3f6",
      "g7f6",
      "g4h5",
      "e8e6",
      "f1e1",
      "c7c5",
      "d4d5",
      "e6e5",
      "c3c4",
      "e5d4",
      "a3e3",
      "d4h4"
    ],
    "eval": {
      "type": "cp",
      "value": 60
    }
  },
  "hangingPieces": {
    "w": [
      "f1"
    ],
    "b": []
  }
},
};

const move_23_b: GameMove = {
  analyzerMoveType: "best",
  expectedMoveType: "best",
  expectedComment: null,
  moveIndex: 45,
  position: {
  "color": "b",
  "san": "Nfxg4",
  "before": "r3qr1k/ppp3pp/1b3n2/8/3P2BB/Q1P1nRN1/PP4PP/4R1K1 b - - 14 23",
  "after": "r3qr1k/ppp3pp/1b6/8/3P2nB/Q1P1nRN1/PP4PP/4R1K1 w - - 0 24",
  "from": "f6",
  "to": "g4",
  "piece": "n",
  "flags": "c",
  "lan": "f6g4",
  "isBigPawn": false,
  "isCapture": true,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Rxf8+",
  "lines": [
    "Rxf8+",
    "Qxf8",
    "Qxf8+",
    "Rxf8",
    "h3",
    "Nc2",
    "Re2",
    "Nxd4",
    "cxd4",
    "Bxd4+",
    "Kh1",
    "Ne3",
    "Bg5",
    "Nf1",
    "Nxf1",
    "Rxf1+",
    "Kh2"
  ],
  "eval": {
    "type": "cp",
    "value": -155
  },
  "secondBest": {
    "lines": [
      "a3f8",
      "e8f8",
      "f3f8",
      "a8f8",
      "h2h3",
      "e3c2",
      "e1e2",
      "c2d4",
      "c3d4",
      "b6d4",
      "g1h1",
      "g4e3",
      "h4g5",
      "e3f1",
      "g3f1",
      "f8f1",
      "h1h2",
      "h7h6",
      "g5e3",
      "d4e5",
      "g2g3"
    ],
    "eval": {
      "type": "cp",
      "value": -160
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": -158
  },
  "bestMove": "Nfxg4",
  "secondBest": {
    "lines": [
      "b6d4",
      "c3d4",
      "f6g4",
      "e1e3",
      "g4e3",
      "f3e3",
      "e8d7",
      "e3e4",
      "f8e8",
      "h4e7",
      "c7c5",
      "e7c5",
      "e8e4",
      "g3e4",
      "a8e8"
    ],
    "eval": {
      "type": "cp",
      "value": 219
    }
  },
  "hangingPieces": {
    "b": [
      "e3"
    ],
    "w": []
  }
},
};

const move_24_w: GameMove = {
  analyzerMoveType: "best",
  expectedMoveType: "best",
  expectedComment: null,
  moveIndex: 46,
  position: {
  "color": "w",
  "san": "Rxf8+",
  "before": "r3qr1k/ppp3pp/1b6/8/3P2nB/Q1P1nRN1/PP4PP/4R1K1 w - - 0 24",
  "after": "r3qR1k/ppp3pp/1b6/8/3P2nB/Q1P1n1N1/PP4PP/4R1K1 b - - 0 24",
  "from": "f3",
  "to": "f8",
  "piece": "r",
  "flags": "c",
  "lan": "f3f8",
  "isBigPawn": false,
  "isCapture": true,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Qxf8",
  "lines": [
    "Qxf8",
    "Qxf8+",
    "Rxf8",
    "h3",
    "Nc2",
    "Re2",
    "Nxd4",
    "cxd4",
    "Bxd4+",
    "Kh1",
    "Ne5",
    "b4",
    "Kg8",
    "Re4",
    "Bb2",
    "Nh5"
  ],
  "eval": {
    "type": "cp",
    "value": -159
  },
  "secondBest": {
    "lines": [],
    "eval": {
      "type": "cp",
      "value": 0
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": -155
  },
  "bestMove": "Rxf8+",
  "secondBest": {
    "lines": [
      "a3f8",
      "e8f8",
      "f3f8",
      "a8f8",
      "h2h3",
      "e3c2",
      "e1e2",
      "c2d4",
      "c3d4",
      "b6d4",
      "g1h1",
      "g4e3",
      "h4g5",
      "e3f1",
      "g3f1",
      "f8f1",
      "h1h2",
      "h7h6",
      "g5e3",
      "d4e5",
      "g2g3"
    ],
    "eval": {
      "type": "cp",
      "value": -160
    }
  },
  "hangingPieces": {
    "w": [],
    "b": []
  }
},
};

const move_24_b: GameMove = {
  analyzerMoveType: "forcing",
  expectedMoveType: "forcing",
  expectedComment: null,
  moveIndex: 47,
  position: {
  "color": "b",
  "san": "Qxf8",
  "before": "r3qR1k/ppp3pp/1b6/8/3P2nB/Q1P1n1N1/PP4PP/4R1K1 b - - 0 24",
  "after": "r4q1k/ppp3pp/1b6/8/3P2nB/Q1P1n1N1/PP4PP/4R1K1 w - - 0 25",
  "from": "e8",
  "to": "f8",
  "piece": "q",
  "flags": "c",
  "lan": "e8f8",
  "isBigPawn": false,
  "isCapture": true,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Qxf8+",
  "lines": [
    "Qxf8+",
    "Rxf8",
    "h3",
    "Nc2",
    "Re2",
    "Nxd4",
    "cxd4",
    "Bxd4+",
    "Kh1",
    "Ne5",
    "Be7",
    "Rf7",
    "Bg5",
    "h6",
    "Be3"
  ],
  "eval": {
    "type": "cp",
    "value": -132
  },
  "secondBest": {
    "lines": [
      "e1e2",
      "f8a3",
      "b2a3",
      "e3d5",
      "g3f5",
      "d5c3",
      "e2e7",
      "c3d5",
      "e7g7"
    ],
    "eval": {
      "type": "cp",
      "value": -403
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": -159
  },
  "bestMove": "Qxf8",
  "secondBest": {
    "lines": [],
    "eval": {
      "type": "cp",
      "value": 0
    }
  },
  "hangingPieces": {
    "b": [
      "e8"
    ],
    "w": [
      "f8"
    ]
  }
},
};

const move_25_w: GameMove = {
  analyzerMoveType: "best",
  expectedMoveType: "best",
  expectedComment: null,
  moveIndex: 48,
  position: {
  "color": "w",
  "san": "Qxf8+",
  "before": "r4q1k/ppp3pp/1b6/8/3P2nB/Q1P1n1N1/PP4PP/4R1K1 w - - 0 25",
  "after": "r4Q1k/ppp3pp/1b6/8/3P2nB/2P1n1N1/PP4PP/4R1K1 b - - 0 25",
  "from": "a3",
  "to": "f8",
  "piece": "q",
  "flags": "c",
  "lan": "a3f8",
  "isBigPawn": false,
  "isCapture": true,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Rxf8",
  "lines": [
    "Rxf8",
    "h3",
    "Nc2",
    "Re2",
    "Nxd4",
    "cxd4",
    "Bxd4+",
    "Kh1",
    "Ne3",
    "Be7",
    "Nf1",
    "Nxf1",
    "Rxf1+",
    "Kh2",
    "Kg8",
    "Kg3",
    "Kf7"
  ],
  "eval": {
    "type": "cp",
    "value": -197
  },
  "secondBest": {
    "lines": [],
    "eval": {
      "type": "cp",
      "value": 0
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": -132
  },
  "bestMove": "Qxf8+",
  "secondBest": {
    "lines": [
      "e1e2",
      "f8a3",
      "b2a3",
      "e3d5",
      "g3f5",
      "d5c3",
      "e2e7",
      "c3d5",
      "e7g7"
    ],
    "eval": {
      "type": "cp",
      "value": -403
    }
  },
  "hangingPieces": {
    "w": [],
    "b": []
  }
},
};

const move_25_b: GameMove = {
  analyzerMoveType: "forcing",
  expectedMoveType: "forcing",
  expectedComment: null,
  moveIndex: 49,
  position: {
  "color": "b",
  "san": "Rxf8",
  "before": "r4Q1k/ppp3pp/1b6/8/3P2nB/2P1n1N1/PP4PP/4R1K1 b - - 0 25",
  "after": "5r1k/ppp3pp/1b6/8/3P2nB/2P1n1N1/PP4PP/4R1K1 w - - 0 26",
  "from": "a8",
  "to": "f8",
  "piece": "r",
  "flags": "c",
  "lan": "a8f8",
  "isBigPawn": false,
  "isCapture": true,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "h3",
  "lines": [
    "h3",
    "Nc2",
    "Re2",
    "Nxd4",
    "cxd4",
    "Bxd4+",
    "Kh1",
    "Ne5",
    "Be7",
    "Rf7",
    "Bg5",
    "h6",
    "Be3"
  ],
  "eval": {
    "type": "cp",
    "value": -172
  },
  "secondBest": {
    "lines": [
      "h4e7",
      "f8e8",
      "e7h4",
      "e8g8",
      "h4g5",
      "e3d5",
      "g3f5"
    ],
    "eval": {
      "type": "cp",
      "value": -298
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": -197
  },
  "bestMove": "Rxf8",
  "secondBest": {
    "lines": [],
    "eval": {
      "type": "cp",
      "value": 0
    }
  },
  "hangingPieces": {
    "b": [
      "a8"
    ],
    "w": [
      "f8"
    ]
  }
},
};

const move_26_w: GameMove = {
  analyzerMoveType: "best",
  expectedMoveType: "best",
  expectedComment: null,
  moveIndex: 50,
  position: {
  "color": "w",
  "san": "h3",
  "before": "5r1k/ppp3pp/1b6/8/3P2nB/2P1n1N1/PP4PP/4R1K1 w - - 0 26",
  "after": "5r1k/ppp3pp/1b6/8/3P2nB/2P1n1NP/PP4P1/4R1K1 b - - 0 26",
  "from": "h2",
  "to": "h3",
  "piece": "p",
  "flags": "n",
  "lan": "h2h3",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Nc2",
  "lines": [
    "Nc2",
    "Re2",
    "Nxd4",
    "cxd4",
    "Bxd4+",
    "Kh1",
    "Ne5",
    "b4",
    "Ng6",
    "Be7",
    "Nxe7",
    "Rxe7",
    "Kg8",
    "Rxc7",
    "Be5"
  ],
  "eval": {
    "type": "cp",
    "value": -164
  },
  "secondBest": {
    "lines": [
      "c7c5",
      "h4e7",
      "f8f2",
      "e1e3",
      "c5d4",
      "c3d4",
      "f2b2",
      "e3e4",
      "b2b1",
      "g3f1",
      "g4e3",
      "e4e3",
      "b6d4"
    ],
    "eval": {
      "type": "cp",
      "value": -123
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": -172
  },
  "bestMove": "h3",
  "secondBest": {
    "lines": [
      "h4e7",
      "f8e8",
      "e7h4",
      "e8g8",
      "h4g5",
      "e3d5",
      "g3f5"
    ],
    "eval": {
      "type": "cp",
      "value": -298
    }
  },
  "hangingPieces": {
    "w": [],
    "b": []
  }
},
};

const move_26_b: GameMove = {
  analyzerMoveType: "best",
  expectedMoveType: "best",
  expectedComment: null,
  moveIndex: 51,
  position: {
  "color": "b",
  "san": "Nc2",
  "before": "5r1k/ppp3pp/1b6/8/3P2nB/2P1n1NP/PP4P1/4R1K1 b - - 0 26",
  "after": "5r1k/ppp3pp/1b6/8/3P2nB/2P3NP/PPn3P1/4R1K1 w - - 1 27",
  "from": "e3",
  "to": "c2",
  "piece": "n",
  "flags": "n",
  "lan": "e3c2",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Re2",
  "lines": [
    "Re2",
    "Nxd4",
    "cxd4",
    "Bxd4+",
    "Kh1",
    "Ne5",
    "Bg5",
    "Ng6",
    "Ne4",
    "Rf1+",
    "Kh2",
    "Ra1",
    "Nc3",
    "Kg8"
  ],
  "eval": {
    "type": "cp",
    "value": -162
  },
  "secondBest": {
    "lines": [
      "e1e4",
      "g4e3",
      "h4g5",
      "e3d5",
      "e4e2",
      "c2d4",
      "c3d4",
      "b6d4",
      "g1h2",
      "h7h6",
      "g5c1",
      "c7c6"
    ],
    "eval": {
      "type": "cp",
      "value": -232
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": -164
  },
  "bestMove": "Nc2",
  "secondBest": {
    "lines": [
      "c7c5",
      "h4e7",
      "f8f2",
      "e1e3",
      "c5d4",
      "c3d4",
      "f2b2",
      "e3e4",
      "b2b1",
      "g3f1",
      "g4e3",
      "e4e3",
      "b6d4"
    ],
    "eval": {
      "type": "cp",
      "value": -123
    }
  },
  "hangingPieces": {
    "b": [
      "g4"
    ],
    "w": []
  }
},
};

const move_27_w: GameMove = {
  analyzerMoveType: "inaccuracy",
  expectedMoveType: "inaccuracy",
  expectedComment: null,
  moveIndex: 52,
  position: {
  "color": "w",
  "san": "Rc1",
  "before": "5r1k/ppp3pp/1b6/8/3P2nB/2P3NP/PPn3P1/4R1K1 w - - 1 27",
  "after": "5r1k/ppp3pp/1b6/8/3P2nB/2P3NP/PPn3P1/2R3K1 b - - 2 27",
  "from": "e1",
  "to": "c1",
  "piece": "r",
  "flags": "n",
  "lan": "e1c1",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Nge3",
  "lines": [
    "Nge3",
    "Be7",
    "Re8",
    "Bg5",
    "Kg8"
  ],
  "eval": {
    "type": "cp",
    "value": -316
  },
  "secondBest": {
    "lines": [
      "c2d4",
      "c3d4",
      "b6d4",
      "g1h1",
      "g4f2",
      "h1h2",
      "d4e5",
      "c1c5",
      "f8e8"
    ],
    "eval": {
      "type": "cp",
      "value": -190
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": -162
  },
  "bestMove": "Re2",
  "secondBest": {
    "lines": [
      "e1e4",
      "g4e3",
      "h4g5",
      "e3d5",
      "e4e2",
      "c2d4",
      "c3d4",
      "b6d4",
      "g1h2",
      "h7h6",
      "g5c1",
      "c7c6"
    ],
    "eval": {
      "type": "cp",
      "value": -232
    }
  },
  "hangingPieces": {
    "w": [
      "e1"
    ],
    "b": [
      "g4"
    ]
  }
},
};

const move_27_b: GameMove = {
  analyzerMoveType: "best",
  expectedMoveType: "best",
  expectedComment: null,
  moveIndex: 53,
  position: {
  "color": "b",
  "san": "Nge3",
  "before": "5r1k/ppp3pp/1b6/8/3P2nB/2P3NP/PPn3P1/2R3K1 b - - 2 27",
  "after": "5r1k/ppp3pp/1b6/8/3P3B/2P1n1NP/PPn3P1/2R3K1 w - - 3 28",
  "from": "g4",
  "to": "e3",
  "piece": "n",
  "flags": "n",
  "lan": "g4e3",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Nf1",
  "lines": [
    "Nf1",
    "Nxf1",
    "Rxc2",
    "Ne3",
    "Re2",
    "Nc4",
    "b3",
    "Nd6",
    "a4",
    "Re8",
    "Rxe8+",
    "Nxe8",
    "b4"
  ],
  "eval": {
    "type": "cp",
    "value": -312
  },
  "secondBest": {
    "lines": [
      "a2a4",
      "h8g8",
      "a4a5",
      "b6a5",
      "h4e7",
      "f8a8",
      "e7c5",
      "a8e8"
    ],
    "eval": {
      "type": "cp",
      "value": -317
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": -316
  },
  "bestMove": "Nge3",
  "secondBest": {
    "lines": [
      "c2d4",
      "c3d4",
      "b6d4",
      "g1h1",
      "g4f2",
      "h1h2",
      "d4e5",
      "c1c5",
      "f8e8"
    ],
    "eval": {
      "type": "cp",
      "value": -190
    }
  },
  "hangingPieces": {
    "b": [
      "g4",
      "c2"
    ],
    "w": []
  }
},
};

const move_28_w: GameMove = {
  analyzerMoveType: "inaccuracy",
  expectedMoveType: "inaccuracy",
  expectedComment: null,
  moveIndex: 54,
  position: {
  "color": "w",
  "san": "Ne4",
  "before": "5r1k/ppp3pp/1b6/8/3P3B/2P1n1NP/PPn3P1/2R3K1 w - - 3 28",
  "after": "5r1k/ppp3pp/1b6/8/3PN2B/2P1n2P/PPn3P1/2R3K1 b - - 4 28",
  "from": "g3",
  "to": "e4",
  "piece": "n",
  "flags": "n",
  "lan": "g3e4",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Rf4",
  "lines": [
    "Rf4",
    "Nc5",
    "Rxh4",
    "Nd7",
    "g5",
    "a4"
  ],
  "eval": {
    "type": "cp",
    "value": -453
  },
  "secondBest": {
    "lines": [
      "h7h6",
      "h4g3",
      "c7c6"
    ],
    "eval": {
      "type": "cp",
      "value": -300
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": -312
  },
  "bestMove": "Nf1",
  "secondBest": {
    "lines": [
      "a2a4",
      "h8g8",
      "a4a5",
      "b6a5",
      "h4e7",
      "f8a8",
      "e7c5",
      "a8e8"
    ],
    "eval": {
      "type": "cp",
      "value": -317
    }
  },
  "hangingPieces": {
    "w": [],
    "b": []
  }
},
};

const move_28_b: GameMove = {
  analyzerMoveType: "inaccuracy",
  expectedMoveType: "inaccuracy",
  expectedComment: null,
  moveIndex: 55,
  position: {
  "color": "b",
  "san": "Re8",
  "before": "5r1k/ppp3pp/1b6/8/3PN2B/2P1n2P/PPn3P1/2R3K1 b - - 4 28",
  "after": "4r2k/ppp3pp/1b6/8/3PN2B/2P1n2P/PPn3P1/2R3K1 w - - 5 29",
  "from": "f8",
  "to": "e8",
  "piece": "r",
  "flags": "n",
  "lan": "f8e8",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Nd2",
  "lines": [
    "Nd2",
    "c5",
    "dxc5",
    "Bxc5",
    "Bf2",
    "Bb6",
    "Nf1",
    "Nxf1",
    "Rxc2",
    "Ng3",
    "Bxb6",
    "axb6",
    "Kh2",
    "Nf5",
    "Rd2"
  ],
  "eval": {
    "type": "cp",
    "value": -282
  },
  "secondBest": {
    "lines": [
      "e4c5",
      "b6c5",
      "d4c5",
      "h7h5",
      "c5c6",
      "b7c6",
      "h4g5",
      "h8h7",
      "g5f4",
      "h7g6"
    ],
    "eval": {
      "type": "cp",
      "value": -292
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": -453
  },
  "bestMove": "Rf4",
  "secondBest": {
    "lines": [
      "h7h6",
      "h4g3",
      "c7c6"
    ],
    "eval": {
      "type": "cp",
      "value": -300
    }
  },
  "hangingPieces": {
    "b": [],
    "w": []
  }
},
};

const move_29_w: GameMove = {
  analyzerMoveType: "good",
  expectedMoveType: "good",
  expectedComment: null,
  moveIndex: 56,
  position: {
  "color": "w",
  "san": "Ng5",
  "before": "4r2k/ppp3pp/1b6/8/3PN2B/2P1n2P/PPn3P1/2R3K1 w - - 5 29",
  "after": "4r2k/ppp3pp/1b6/6N1/3P3B/2P1n2P/PPn3P1/2R3K1 b - - 6 29",
  "from": "e4",
  "to": "g5",
  "piece": "n",
  "flags": "n",
  "lan": "e4g5",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "c5",
  "lines": [
    "c5",
    "dxc5",
    "Bxc5",
    "Bf2",
    "Kg8",
    "a4",
    "b6",
    "Nf3",
    "Rd8",
    "b4",
    "Bd6"
  ],
  "eval": {
    "type": "cp",
    "value": -294
  },
  "secondBest": {
    "lines": [
      "h7h6",
      "g5f3",
      "c7c5",
      "d4c5",
      "b6c5",
      "h4f2",
      "c5b6",
      "a2a4",
      "e8d8",
      "a4a5",
      "b6a5"
    ],
    "eval": {
      "type": "cp",
      "value": -272
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": -282
  },
  "bestMove": "Nd2",
  "secondBest": {
    "lines": [
      "e4c5",
      "b6c5",
      "d4c5",
      "h7h5",
      "c5c6",
      "b7c6",
      "h4g5",
      "h8h7",
      "g5f4",
      "h7g6"
    ],
    "eval": {
      "type": "cp",
      "value": -292
    }
  },
  "hangingPieces": {
    "w": [
      "e4"
    ],
    "b": []
  }
},
};

const move_29_b: GameMove = {
  analyzerMoveType: "good",
  expectedMoveType: "good",
  expectedComment: null,
  moveIndex: 57,
  position: {
  "color": "b",
  "san": "Kg8",
  "before": "4r2k/ppp3pp/1b6/6N1/3P3B/2P1n2P/PPn3P1/2R3K1 b - - 6 29",
  "after": "4r1k1/ppp3pp/1b6/6N1/3P3B/2P1n2P/PPn3P1/2R3K1 w - - 7 30",
  "from": "h8",
  "to": "g8",
  "piece": "k",
  "flags": "n",
  "lan": "h8g8",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Bf2",
  "lines": [
    "Bf2",
    "c6",
    "a4",
    "h5",
    "Nf3",
    "Bc7"
  ],
  "eval": {
    "type": "cp",
    "value": -280
  },
  "secondBest": {
    "lines": [
      "g5f3",
      "c7c5",
      "d4c5",
      "b6c5",
      "h4f2",
      "b7b6",
      "f3e1",
      "e3d1",
      "c1d1",
      "e8e1",
      "d1e1",
      "c2e1",
      "b2b4",
      "c5f2",
      "g1f2",
      "e1d3",
      "f2e3"
    ],
    "eval": {
      "type": "cp",
      "value": -308
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": -294
  },
  "bestMove": "c5",
  "secondBest": {
    "lines": [
      "h7h6",
      "g5f3",
      "c7c5",
      "d4c5",
      "b6c5",
      "h4f2",
      "c5b6",
      "a2a4",
      "e8d8",
      "a4a5",
      "b6a5"
    ],
    "eval": {
      "type": "cp",
      "value": -272
    }
  },
  "hangingPieces": {
    "b": [],
    "w": []
  }
},
};

const move_30_w: GameMove = {
  analyzerMoveType: "inaccuracy",
  expectedMoveType: "inaccuracy",
  expectedComment: null,
  moveIndex: 58,
  position: {
  "color": "w",
  "san": "Kf2",
  "before": "4r1k1/ppp3pp/1b6/6N1/3P3B/2P1n2P/PPn3P1/2R3K1 w - - 7 30",
  "after": "4r1k1/ppp3pp/1b6/6N1/3P3B/2P1n2P/PPn2KP1/2R5 b - - 8 30",
  "from": "g1",
  "to": "f2",
  "piece": "k",
  "flags": "n",
  "lan": "g1f2",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "h6",
  "lines": [
    "h6",
    "Kg1",
    "hxg5",
    "Bxg5",
    "c5",
    "Bxe3",
    "Nxe3"
  ],
  "eval": {
    "type": "cp",
    "value": -466
  },
  "secondBest": {
    "lines": [
      "c7c5",
      "d4c5",
      "b6c5",
      "f2f3",
      "e8f8",
      "f3e4",
      "e3g2",
      "h4g3",
      "f8e8",
      "e4d5",
      "c5b6",
      "d5d6",
      "g2e3",
      "d6d7",
      "e8d8",
      "d7e6"
    ],
    "eval": {
      "type": "cp",
      "value": -414
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": -280
  },
  "bestMove": "Bf2",
  "secondBest": {
    "lines": [
      "g5f3",
      "c7c5",
      "d4c5",
      "b6c5",
      "h4f2",
      "b7b6",
      "f3e1",
      "e3d1",
      "c1d1",
      "e8e1",
      "d1e1",
      "c2e1",
      "b2b4",
      "c5f2",
      "g1f2",
      "e1d3",
      "f2e3"
    ],
    "eval": {
      "type": "cp",
      "value": -308
    }
  },
  "hangingPieces": {
    "w": [],
    "b": []
  }
},
};

const move_30_b: GameMove = {
  analyzerMoveType: "good",
  expectedMoveType: "good",
  expectedComment: null,
  moveIndex: 59,
  position: {
  "color": "b",
  "san": "c5",
  "before": "4r1k1/ppp3pp/1b6/6N1/3P3B/2P1n2P/PPn2KP1/2R5 b - - 8 30",
  "after": "4r1k1/pp4pp/1b6/2p3N1/3P3B/2P1n2P/PPn2KP1/2R5 w - - 0 31",
  "from": "c7",
  "to": "c5",
  "piece": "p",
  "flags": "b",
  "lan": "c7c5",
  "isBigPawn": true,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "dxc5",
  "lines": [
    "dxc5",
    "Bxc5",
    "Kf3",
    "Rf8+",
    "Ke4",
    "Nxg2",
    "Bg3",
    "Re8+",
    "Kf3",
    "Nge1+",
    "Bxe1",
    "Nxe1+",
    "Rxe1",
    "Rxe1"
  ],
  "eval": {
    "type": "cp",
    "value": -419
  },
  "secondBest": {
    "lines": [
      "d4d5",
      "h7h6",
      "d5d6",
      "h6g5",
      "h4g5",
      "g8f7",
      "f2f3",
      "f7g6",
      "d6d7",
      "e8f8",
      "g5f4"
    ],
    "eval": {
      "type": "cp",
      "value": -423
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": -466
  },
  "bestMove": "h6",
  "secondBest": {
    "lines": [
      "c7c5",
      "d4c5",
      "b6c5",
      "f2f3",
      "e8f8",
      "f3e4",
      "e3g2",
      "h4g3",
      "f8e8",
      "e4d5",
      "c5b6",
      "d5d6",
      "g2e3",
      "d6d7",
      "e8d8",
      "d7e6"
    ],
    "eval": {
      "type": "cp",
      "value": -414
    }
  },
  "hangingPieces": {
    "b": [],
    "w": []
  }
},
};

const move_31_w: GameMove = {
  analyzerMoveType: "best",
  expectedMoveType: "best",
  expectedComment: null,
  moveIndex: 60,
  position: {
  "color": "w",
  "san": "dxc5",
  "before": "4r1k1/pp4pp/1b6/2p3N1/3P3B/2P1n2P/PPn2KP1/2R5 w - - 0 31",
  "after": "4r1k1/pp4pp/1b6/2P3N1/7B/2P1n2P/PPn2KP1/2R5 b - - 0 31",
  "from": "d4",
  "to": "c5",
  "piece": "p",
  "flags": "c",
  "lan": "d4c5",
  "isBigPawn": false,
  "isCapture": true,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Bxc5",
  "lines": [
    "Bxc5",
    "Kf3",
    "Rf8+",
    "Ke4",
    "Nxg2",
    "Bg3",
    "Re8+",
    "Kd5",
    "Bb6",
    "Kd6",
    "Nce3",
    "Bh2",
    "Rd8+",
    "Ke6"
  ],
  "eval": {
    "type": "cp",
    "value": -429
  },
  "secondBest": {
    "lines": [
      "b6c7",
      "h4g3",
      "c7g3",
      "f2g3",
      "b7b6",
      "g3f2"
    ],
    "eval": {
      "type": "cp",
      "value": -228
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": -419
  },
  "bestMove": "dxc5",
  "secondBest": {
    "lines": [
      "d4d5",
      "h7h6",
      "d5d6",
      "h6g5",
      "h4g5",
      "g8f7",
      "f2f3",
      "f7g6",
      "d6d7",
      "e8f8",
      "g5f4"
    ],
    "eval": {
      "type": "cp",
      "value": -423
    }
  },
  "hangingPieces": {
    "w": [
      "d4"
    ],
    "b": []
  }
},
};

const move_31_b: GameMove = {
  analyzerMoveType: "best",
  expectedMoveType: "best",
  expectedComment: null,
  moveIndex: 61,
  position: {
  "color": "b",
  "san": "Bxc5",
  "before": "4r1k1/pp4pp/1b6/2P3N1/7B/2P1n2P/PPn2KP1/2R5 b - - 0 31",
  "after": "4r1k1/pp4pp/8/2b3N1/7B/2P1n2P/PPn2KP1/2R5 w - - 0 32",
  "from": "b6",
  "to": "c5",
  "piece": "b",
  "flags": "c",
  "lan": "b6c5",
  "isBigPawn": false,
  "isCapture": true,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Kg1",
  "lines": [
    "Kg1",
    "Nd1+",
    "Kh1",
    "Nce3",
    "Rxd1",
    "Nxd1"
  ],
  "eval": {
    "type": "cp",
    "value": -407
  },
  "secondBest": {
    "lines": [
      "f2f3",
      "e8f8",
      "f3e4",
      "e3g2",
      "h4g3",
      "f8e8",
      "e4d5",
      "c5b6",
      "d5d6",
      "c2e3",
      "g3h2",
      "e8d8",
      "d6e7",
      "e3d5",
      "e7e6",
      "g2e3"
    ],
    "eval": {
      "type": "cp",
      "value": -426
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": -429
  },
  "bestMove": "Bxc5",
  "secondBest": {
    "lines": [
      "b6c7",
      "h4g3",
      "c7g3",
      "f2g3",
      "b7b6",
      "g3f2"
    ],
    "eval": {
      "type": "cp",
      "value": -228
    }
  },
  "hangingPieces": {
    "b": [],
    "w": [
      "c5"
    ]
  }
},
};

const move_32_w: GameMove = {
  analyzerMoveType: "inaccuracy",
  expectedMoveType: "inaccuracy",
  expectedComment: null,
  moveIndex: 62,
  position: {
  "color": "w",
  "san": "Ke2",
  "before": "4r1k1/pp4pp/8/2b3N1/7B/2P1n2P/PPn2KP1/2R5 w - - 0 32",
  "after": "4r1k1/pp4pp/8/2b3N1/7B/2P1n2P/PPn1K1P1/2R5 b - - 1 32",
  "from": "f2",
  "to": "e2",
  "piece": "k",
  "flags": "n",
  "lan": "f2e2",
  "isBigPawn": false,
  "isCapture": false,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Nxg2+",
  "lines": [
    "Nxg2+",
    "Kd3",
    "Bb6",
    "Nf3",
    "Nce3",
    "Bg3",
    "Nf5",
    "Be5"
  ],
  "eval": {
    "type": "cp",
    "value": -491
  },
  "secondBest": {
    "lines": [
      "e3c4",
      "e2d3",
      "c2e3",
      "b2b4",
      "c4e5",
      "d3d2",
      "c5b6",
      "h4g3"
    ],
    "eval": {
      "type": "cp",
      "value": -490
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": -407
  },
  "bestMove": "Kg1",
  "secondBest": {
    "lines": [
      "f2f3",
      "e8f8",
      "f3e4",
      "e3g2",
      "h4g3",
      "f8e8",
      "e4d5",
      "c5b6",
      "d5d6",
      "c2e3",
      "g3h2",
      "e8d8",
      "d6e7",
      "e3d5",
      "e7e6",
      "g2e3"
    ],
    "eval": {
      "type": "cp",
      "value": -426
    }
  },
  "hangingPieces": {
    "w": [],
    "b": []
  }
},
};

const move_32_b: GameMove = {
  analyzerMoveType: "best",
  expectedMoveType: "best",
  expectedComment: null,
  moveIndex: 63,
  position: {
  "color": "b",
  "san": "Nxg2+",
  "before": "4r1k1/pp4pp/8/2b3N1/7B/2P1n2P/PPn1K1P1/2R5 b - - 1 32",
  "after": "4r1k1/pp4pp/8/2b3N1/7B/2P4P/PPn1K1n1/2R5 w - - 0 33",
  "from": "e3",
  "to": "g2",
  "piece": "n",
  "flags": "c",
  "lan": "e3g2",
  "isBigPawn": false,
  "isCapture": true,
  "isEnPassant": false,
  "isKingsideCastle": false,
  "isPromotion": false,
  "isQueensideCastle": false
},
  stockfish: {
  "bestMove": "Kd3",
  "lines": [
    "Kd3",
    "Nxh4",
    "Ne4",
    "Bb6",
    "Kxc2",
    "Rxe4",
    "Rd1",
    "Re8",
    "Rd7"
  ],
  "eval": {
    "type": "cp",
    "value": -514
  },
  "secondBest": {
    "lines": [
      "e2d2",
      "g2h4",
      "d2c2",
      "b7b5",
      "c1e1",
      "e8e1"
    ],
    "eval": {
      "type": "cp",
      "value": -525
    }
  }
},
  prev: {
  "eval": {
    "type": "cp",
    "value": -491
  },
  "bestMove": "Nxg2+",
  "secondBest": {
    "lines": [
      "e3c4",
      "e2d3",
      "c2e3",
      "b2b4",
      "c4e5",
      "d3d2",
      "c5b6",
      "h4g3"
    ],
    "eval": {
      "type": "cp",
      "value": -490
    }
  },
  "hangingPieces": {
    "b": [],
    "w": [
      "g2"
    ]
  }
},
};

describe("Game 2", () => {
  test("1. e4", async () => {
    await check(move_1_w);
  });

  test("1... e5", async () => {
    await check(move_1_b);
  });

  test("2. Nc3", async () => {
    await check(move_2_w);
  });

  test("2... Bc5", async () => {
    await check(move_2_b);
  });

  test("3. Bc4", async () => {
    await check(move_3_w);
  });

  test("3... d6", async () => {
    await check(move_3_b);
  });

  test("4. f4", async () => {
    await check(move_4_w);
  });

  test("4... exf4", async () => {
    await check(move_4_b);
  });

  test("5. Nf3", async () => {
    await check(move_5_w);
  });

  test("5... Nf6", async () => {
    await check(move_5_b);
  });

  test("6. d4", async () => {
    await check(move_6_w);
  });

  test("6... Bb6", async () => {
    await check(move_6_b);
  });

  test("7. O-O", async () => {
    await check(move_7_w);
  });

  test("7... O-O", async () => {
    await check(move_7_b);
  });

  test("8. Bxf4", async () => {
    await check(move_8_w);
  });

  test("8... Bg4", async () => {
    await check(move_8_b);
  });

  test("9. Qd3", async () => {
    await check(move_9_w);
  });

  test("9... Nc6", async () => {
    await check(move_9_b);
  });

  test("10. Ne2", async () => {
    await check(move_10_w);
  });

  test("10... Bxf3", async () => {
    await check(move_10_b);
  });

  test("11. Rxf3", async () => {
    await check(move_11_w);
  });

  test("11... d5", async () => {
    await check(move_11_b);
  });

  test("12. exd5", async () => {
    await check(move_12_w);
  });

  test("12... Nxd5", async () => {
    await check(move_12_b);
  });

  test("13. Bg3", async () => {
    await check(move_13_w);
  });

  test("13... Ndb4", async () => {
    await check(move_13_b);
  });

  test("14. Qb3", async () => {
    await check(move_14_w);
  });

  test("14... Na6", async () => {
    await check(move_14_b);
  });

  test("15. c3", async () => {
    await check(move_15_w);
  });

  test("15... Nab8", async () => {
    await check(move_15_b);
  });

  test("16. Bxf7+", async () => {
    await check(move_16_w);
  });

  test("16... Kh8", async () => {
    await check(move_16_b);
  });

  test("17. Raf1", async () => {
    await check(move_17_w);
  });

  test("17... Nd7", async () => {
    await check(move_17_b);
  });

  test("18. Bh5", async () => {
    await check(move_18_w);
  });

  test("18... Nf6", async () => {
    await check(move_18_b);
  });

  test("19. Qa3", async () => {
    await check(move_19_w);
  });

  test("19... Ne7", async () => {
    await check(move_19_b);
  });

  test("20. Bh4", async () => {
    await check(move_20_w);
  });

  test("20... Ned5", async () => {
    await check(move_20_b);
  });

  test("21. Bg4", async () => {
    await check(move_21_w);
  });

  test("21... Qe8", async () => {
    await check(move_21_b);
  });

  test("22. Ng3", async () => {
    await check(move_22_w);
  });

  test("22... Ne3", async () => {
    await check(move_22_b);
  });

  test("23. Re1", async () => {
    await check(move_23_w);
  });

  test("23... Nfxg4", async () => {
    await check(move_23_b);
  });

  test("24. Rxf8+", async () => {
    await check(move_24_w);
  });

  test("24... Qxf8", async () => {
    await check(move_24_b);
  });

  test("25. Qxf8+", async () => {
    await check(move_25_w);
  });

  test("25... Rxf8", async () => {
    await check(move_25_b);
  });

  test("26. h3", async () => {
    await check(move_26_w);
  });

  test("26... Nc2", async () => {
    await check(move_26_b);
  });

  test("27. Rc1", async () => {
    await check(move_27_w);
  });

  test("27... Nge3", async () => {
    await check(move_27_b);
  });

  test("28. Ne4", async () => {
    await check(move_28_w);
  });

  test("28... Re8", async () => {
    await check(move_28_b);
  });

  test("29. Ng5", async () => {
    await check(move_29_w);
  });

  test("29... Kg8", async () => {
    await check(move_29_b);
  });

  test("30. Kf2", async () => {
    await check(move_30_w);
  });

  test("30... c5", async () => {
    await check(move_30_b);
  });

  test("31. dxc5", async () => {
    await check(move_31_w);
  });

  test("31... Bxc5", async () => {
    await check(move_31_b);
  });

  test("32. Ke2", async () => {
    await check(move_32_w);
  });

  test("32... Nxg2+", async () => {
    await check(move_32_b);
  });
});
